// EmiHttpClient - the transport every generated action/remote call (see
// cpp-action-render.go, unreal dialect) goes through: a thin, typed wrapper
// around FHttpModule, Unreal's own HTTP client. Add "HTTP" to your module's
// Build.cs PublicDependencyModuleNames.
//
// Generated by the Emi compiler - do not edit by hand.
#pragma once

#include "CoreMinimal.h"
#include "HttpModule.h"
#include "Interfaces/IHttpRequest.h"
#include "Interfaces/IHttpResponse.h"

// Carries the base url + default headers for every generated action method -
// build one per client instance, or rely on FEmiClientConfig::Default() for a
// single process-wide instance (mirrors EmiClientConfig in the generic dialect).
class FEmiClientConfig {
public:
    FString BaseUrl;
    TMap<FString, FString> DefaultHeaders;

    static FEmiClientConfig& Default() {
        static FEmiClientConfig Instance;
        return Instance;
    }
};

// Joins a base url with a (possibly already-parameterized) path, collapsing
// duplicate slashes at the seam.
inline FString EmiBuildUrl(const FString& BaseUrl, const FString& TemplateUrl) {
    if (BaseUrl.IsEmpty()) return TemplateUrl;
    FString Base = BaseUrl;
    while (Base.EndsWith(TEXT("/"))) Base.LeftChopInline(1);
    FString Path = TemplateUrl;
    while (Path.StartsWith(TEXT("/"))) Path.RightChopInline(1);
    return Base + TEXT("/") + Path;
}

using FEmiHttpResponseCallback = TFunction<void(bool bSucceeded, int32 StatusCode, const FString& Body)>;

// Fires `OnComplete` on the game thread once the request finishes (matching
// every other Unreal-idiomatic async HTTP call) - `bSucceeded` is false only on a
// transport-level failure (connection/DNS/etc.), independent of the HTTP status
// code itself (check StatusCode for a non-2xx response).
inline void EmiHttpRequest(
    const FString& Method,
    const FString& Url,
    const FString& JsonBody,
    const TMap<FString, FString>& Headers,
    const FEmiClientConfig& Config,
    FEmiHttpResponseCallback OnComplete
) {
    TSharedRef<IHttpRequest, ESPMode::ThreadSafe> Request = FHttpModule::Get().CreateRequest();
    Request->SetURL(Url);
    Request->SetVerb(Method);

    for (const auto& Header : Config.DefaultHeaders) {
        Request->SetHeader(Header.Key, Header.Value);
    }
    for (const auto& Header : Headers) {
        Request->SetHeader(Header.Key, Header.Value);
    }
    if (!JsonBody.IsEmpty()) {
        Request->SetHeader(TEXT("Content-Type"), TEXT("application/json"));
        Request->SetContentAsString(JsonBody);
    }

    Request->OnProcessRequestComplete().BindLambda(
        [OnComplete](FHttpRequestPtr, FHttpResponsePtr Response, bool bConnectedSuccessfully) {
            if (!bConnectedSuccessfully || !Response.IsValid()) {
                OnComplete(false, 0, FString());
                return;
            }
            OnComplete(true, Response->GetResponseCode(), Response->GetContentAsString());
        });

    Request->ProcessRequest();
}
