// EmiWebSocketX - a thin, typed wrapper around Unreal's own IWebSocket
// (WebSockets module), backing every `method: reactive` action in the unreal
// dialect (see cpp-action-reactive-render.go) - the same role EmiWebSocketX plays
// in the Swift target (lib/swift/swift-websocket-runtime.go) and the generic C++
// dialect's own EmiWebSocketX (cpp-include/generic/EmiWebSocketX.hpp). Add
// "WebSockets" to your module's Build.cs PublicDependencyModuleNames.
//
// Generated by the Emi compiler - do not edit by hand.
#pragma once

#include "CoreMinimal.h"
#include "IWebSocket.h"
#include "WebSocketsModule.h"

class FEmiWebSocketX {
public:
    DECLARE_DELEGATE_OneParam(FOnMessage, const FString& /* RawJson */);
    DECLARE_DELEGATE_OneParam(FOnError, const FString& /* Message */);
    DECLARE_DELEGATE(FOnClose);

    FOnMessage OnMessage;
    FOnError OnError;
    FOnClose OnClose;

    // `Url` is a `ws://`/`wss://` url (build one with EmiBuildUrl + a scheme
    // swap - see the generated `*Socket::Create` helper).
    void Connect(const FString& Url, const TMap<FString, FString>& Headers = {}) {
        TArray<FString> Protocols;
        Socket = FWebSocketsModule::Get().CreateWebSocket(Url, FString(), Headers);

        Socket->OnMessage().AddLambda([this](const FString& Message) {
            OnMessage.ExecuteIfBound(Message);
        });
        Socket->OnConnectionError().AddLambda([this](const FString& Error) {
            OnError.ExecuteIfBound(Error);
        });
        Socket->OnClosed().AddLambda([this](int32, const FString&, bool) {
            OnClose.ExecuteIfBound();
        });

        Socket->Connect();
    }

    // Sends one text frame - the wire format every generated dto's JSON payload
    // (via FJsonObjectConverter::UStructToJsonObjectString) round-trips through.
    void Send(const FString& Text) {
        if (Socket.IsValid() && Socket->IsConnected()) {
            Socket->Send(Text);
        }
    }

    bool IsOpen() const { return Socket.IsValid() && Socket->IsConnected(); }

    void Close() {
        if (Socket.IsValid()) {
            Socket->Close();
        }
    }

private:
    TSharedPtr<IWebSocket> Socket;
};
