package kotlin

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/torabian/emi/lib/core"
)

type RecognizedComplex struct {
	Symbol string

	ImportLocation string
}

type renderedClass struct {
	ClassName      string
	Fields         []renderedField
	LateInitFields []renderedField
	Signature      string
	GoDoc          string
	SubClasses     []renderedClass
	ClassTypePath  string
	ClassNamePath  string
}

// Is is a bit weird function I am adding to capture type.
// basically, Name.Object.Item will become NameType.ObjectType.ItemType
func treeAsType(treeLocation string) string {
	parts := strings.Split(treeLocation, ".")
	for i, p := range parts {
		parts[i] = p + "Type"
	}
	return strings.Join(parts, ".")
}

type commonClassContext struct {

	// The class name which will be used to generate nested classes,
	// in case of array or object
	RootClassName string

	// List of allowed complexes type to be used on fields
	RecognizedComplexes []RecognizedComplex

	// the package location of the emi runtime.
	// If the project wants to copy that and override we use this
	EmiLocation string
}

func renderClasses(fields []*core.EmiField, className, treeLocation string, fieldDepth string, prefixName string, ctx core.MicroGenContext, goctx commonClassContext) []renderedClass {

	GoDoc := NewGoDoc("  ").Add(fmt.Sprintf("The base class definition for %v", core.ToLower(className)))
	signature := fmt.Sprintf("@Serializable\r\ndata class %v", prefixName)

	fieldsRendered := renderFieldsShallow(fields, treeLocation, fieldDepth, ctx, goctx)

	currentClass := renderedClass{
		ClassName:     core.ToUpper(className),
		Fields:        fieldsRendered,
		ClassNamePath: treeLocation,
		ClassTypePath: treeAsType(treeLocation),
		GoDoc:         GoDoc.String(),
		Signature:     signature,
	}

	for _, f := range fields {
		if f != nil && (f.Type == core.FieldTypeObject || f.Type == core.FieldTypeObjectNullable || f.Type == core.FieldTypeArray || f.Type == core.FieldTypeArrayNullable) {
			childName := core.ToUpper(f.Name)
			newDepth := fieldDepth + f.Name
			if fieldDepth == "" {
				newDepth = f.Name
			}
			currentClass.SubClasses = append(currentClass.SubClasses, renderClasses(f.Fields, childName, treeLocation+childName, newDepth, prefixName+childName, ctx, goctx)...)
		}
	}

	return []renderedClass{currentClass}
}

// CollectComplexClasses finds every `type: complex` field's class name (mirrors Go's
// own CollectComplexClasses in go-struct-generator-common.go). The gate used to be
// `strings.Contains(field.Complex, "+")`, which silently skipped the plain
// `complex: Money` convention already used by examples/emi-entity/entity.emi.yml (no
// "+") - only match on the field actually being `type: complex`, same as Go.
func CollectComplexClasses(fields []*core.EmiField) []string {
	var result []string

	var walk func(f []*core.EmiField)
	walk = func(f []*core.EmiField) {
		for _, field := range f {
			if field == nil {
				continue
			}

			if field.Complex != "" && field.Type == core.FieldTypeComplex {
				result = append(result, strings.ReplaceAll(field.Complex, "+", ""))
			}
			if len(field.Fields) > 0 {
				walk(field.Fields)
			}
		}
	}

	walk(fields)
	return result
}

func findComplexLocation(complexName string, goctx commonClassContext) string {

	for _, item := range goctx.RecognizedComplexes {
		if item.Symbol == complexName {
			return item.ImportLocation
		}
	}

	// If no location, then basically skip it.
	return ""
}

// kotlinCollectTargetDeps walks fields for one/collection "target:" relations - like
// core.CollectTargets, but keeps *core.EmiField in hand (CollectTargets only returns
// bare target-name strings) so it can tell a same-module reference (no Module set -
// resolves to a sibling class in the exact same generated package, so no import is
// needed - see CombineJavaImport's Objects-carrying skip) from a cross-module one
// (Module set - needs a real `import <module>.<Target>` line, since it's a different
// Kotlin package generated by a separate `emi kotlin --pkg <module>` invocation).
// currentName excludes a self-reference to the dto's own root class, same as
// core.CollectTargets.
func kotlinCollectTargetDeps(fields []*core.EmiField, currentName string) []core.CodeChunkDependency {
	var deps []core.CodeChunkDependency

	var walk func(f []*core.EmiField)
	walk = func(f []*core.EmiField) {
		for _, field := range f {
			if field == nil {
				continue
			}

			if field.Target != "" && field.Target != currentName {
				if field.Module != "" {
					deps = append(deps, core.CodeChunkDependency{
						Location: field.Module + "." + field.Target,
					})
				} else {
					deps = append(deps, core.CodeChunkDependency{
						Objects: []string{field.Target},
					})
				}
			}

			if len(field.Fields) > 0 {
				walk(field.Fields)
			}
		}
	}

	walk(fields)
	return deps
}

// Generates a class with getters and setters.
func KotlinCommonStructGenerator(fields []*core.EmiField, ctx core.MicroGenContext, goctx commonClassContext) (*core.CodeChunkCompiled, error) {

	res := &core.CodeChunkCompiled{
		CodeChunkDependensies: []core.CodeChunkDependency{
			{
				Location: "kotlinx.serialization.*",
			},
			{
				Location: "kotlinx.serialization.json.*",
			},
			{
				Location: "emikot.MaybeField",
			},
			{
				Location: "emikot.Maybe",
			},
		},
	}

	usedComplexes := CollectComplexClasses(fields)
	for _, item := range usedComplexes {

		location := findComplexLocation(item, goctx)
		if location == "" {
			continue
		}

		// Objects left empty (unlike the dto/entity target case below): a complex
		// class always lives in a real, separate location the developer supplies -
		// CombineJavaImport only skips Objects-carrying deps (same-package sibling
		// classes), so a plain Location-only dependency here becomes a real
		// `import <location>` line, matching Go's own convention (see
		// go-struct-generator-common.go).
		res.CodeChunkDependensies = append(res.CodeChunkDependensies, core.CodeChunkDependency{
			Objects:  []string{},
			Location: location,
		})
	}

	res.CodeChunkDependensies = append(res.CodeChunkDependensies, kotlinCollectTargetDeps(fields, goctx.RootClassName)...)

	renderedClasses := renderClasses(fields, goctx.RootClassName, goctx.RootClassName, "", core.ToUpper(goctx.RootClassName), ctx, goctx)
	if len(renderedClasses) > 0 {
		res.Tokens = append(res.Tokens, core.GeneratedScriptToken{Name: TOKEN_ROOT_CLASS, Value: renderedClasses[0].ClassName})
		res.Tokens = append(res.Tokens, core.GeneratedScriptToken{Name: TOKEN_OBJ_CLASS, Value: renderedClasses[0].ClassName})
	}

	const tmpl = `

{{ if .emiRuntimeLocation }}
	import emi "{{ .emiRuntimeLocation }}"
{{ end }}

{{ define "printClass" }}
{{ .GoDoc }}
{{ .Signature  }} (
	{{ range .Fields }}
		{{ .PrivateField }},
	{{ end }}
)

	{{ range .SubClasses }}
		{{ template "printClass" . }}
	{{ end }}

	

{{ end }}
{{ range .renderedClasses }}
	{{ template "printClass" . }}
{{ end }}

  
`

	t := template.Must(template.New("action").Funcs(core.CommonMap).Parse(tmpl))

	var buf bytes.Buffer
	if err := t.Execute(&buf, core.H{
		"renderedClasses":    renderedClasses,
		"emiRuntimeLocation": goctx.EmiLocation,
	}); err != nil {
		return nil, err
	}

	result := buf.String()

	res.ActualScript = []byte(result)
	res.SuggestedFileName = goctx.RootClassName + ".kt"

	return res, nil
}
