// Package emigorm holds the gorm-specific runtime primitives generated entity
// Create/Update functions call into. It's deliberately a separate package from emigo:
// emigo is the wasm-safe, dependency-light runtime shared by every generated type
// (actions, dtos, entities alike), while emigorm depends on gorm.io/gorm and only makes
// sense wherever an entity is actually persisted through gorm.
package emigorm

import (
	"reflect"
)

// Every entity/child-row struct ApplyEntityGormTags touches gets two identity fields
// (see lib/golang/go-entity-default-fields.go), and this package reads/writes them by
// name, uniformly, without needing per-type accessor methods generated:
//
//   - Id (int64) is the real gorm primary key - autoIncrement, DB-assigned, never known
//     by a caller ahead of time. It's what LinkerId/foreignKey/references columns
//     actually join on, since a small integer keeps indexes smaller and joins faster
//     than a UUID would.
//   - UniqueId (string) is the public identifier - a UUID, generated by Postgres
//     itself via a column default - and the only identity a caller (API/CLI) ever
//     actually has. It's what the reconcile helpers below match an incoming item
//     against an existing row with.

// indirect dereferences pointers down to the underlying addressable struct value.
func indirect(v reflect.Value) reflect.Value {
	for v.Kind() == reflect.Pointer {
		if v.IsNil() {
			return v
		}
		v = v.Elem()
	}
	return v
}

// uniqueIdOf reads the UniqueId field off any entity/child-row struct (or pointer to
// one).
func uniqueIdOf(v any) string {
	rv := indirect(reflect.ValueOf(v))
	if !rv.IsValid() || rv.Kind() != reflect.Struct {
		return ""
	}
	f := rv.FieldByName("UniqueId")
	if !f.IsValid() || f.Kind() != reflect.String {
		return ""
	}
	return f.String()
}

// idOf reads the Id field off any entity/child-row struct (or pointer to one).
func idOf(v any) int64 {
	rv := indirect(reflect.ValueOf(v))
	if !rv.IsValid() || rv.Kind() != reflect.Struct {
		return 0
	}
	f := rv.FieldByName("Id")
	if !f.IsValid() || f.Kind() != reflect.Int64 {
		return 0
	}
	return f.Int()
}

// setId writes id into v's Id field (v must be a pointer to a struct) - used to make an
// incoming item that matched an existing row (by UniqueId) carry that row's *real*
// primary key before Save(), so gorm updates it in place instead of attempting to
// insert a duplicate (gorm's Save() decides insert-vs-update from the primary key
// alone, and a caller never has - or sends back - the internal Id itself).
func setId(v any, id int64) {
	rv := indirect(reflect.ValueOf(v))
	if !rv.IsValid() || rv.Kind() != reflect.Struct {
		return
	}
	f := rv.FieldByName("Id")
	if f.IsValid() && f.Kind() == reflect.Int64 && f.CanSet() {
		f.SetInt(id)
	}
}

// setInt64Field writes value into the named int64 field of v (a pointer to a struct) -
// used to stamp the LinkerId column back onto array children before saving them.
func setInt64Field(v any, name string, value int64) {
	rv := indirect(reflect.ValueOf(v))
	if !rv.IsValid() || rv.Kind() != reflect.Struct {
		return
	}
	f := rv.FieldByName(name)
	if f.IsValid() && f.Kind() == reflect.Int64 && f.CanSet() {
		f.SetInt(value)
	}
}
