package org.example.sdkgen

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.encodeToString
import kotlinx.serialization.decodeFromString
import unknownpackage.AddressDto
import unknownpackage.TeamDto
import unknownpackage.MemberDtoBadges
import unknownpackage.BuildProfileActionMeta
import unknownpackage.LookupAddressActionMeta
import unknownpackage.TeamCreateActionMeta
import unknownpackage.TeamGetActionMeta
import unknownpackage.TeamUpdateActionMeta
import unknownpackage.MemberCreateActionMeta
import unknownpackage.MemberGetActionMeta
import unknownpackage.MemberBrowseActionMeta
import emikot.Maybe
import emikot.MaybeField
import kotlin.test.Test
import kotlin.test.assertEquals

/**
 * Smoke tests for the code generated by `make gen` (see ../../Makefile) out of
 * definitions.emi.yml. These don't test the emi compiler itself (that lives in the
 * Go codebase) - they exist to catch the generated Kotlin actually behaving as the
 * .emi.yml describes: field shapes, optional-field wrapping and action metadata
 * (name/url/method) for actions that came from both hand-written actions and the
 * ones synthesized from entities (see lib/core/preprocess-entity-actions.go).
 */
class SdkgenTest {

    private val json = Json { encodeDefaults = true }

    // AddressDto has no relation/enum fields, so it's a clean round trip for its plain
    // scalars. The MaybeField<String> field (postcode) round-trips its *content*
    // rather than an equal MaybeField instance: MaybeFieldSerializer.deserialize (see
    // common.kt) decodes a present value into a raw JsonElement rather than a String,
    // since it's a serializer for the type-erased MaybeField<Any?> - that's why it's
    // asserted separately via JsonPrimitive.content below instead of full data-class
    // equality.
    @Test
    fun `AddressDto survives a JSON round trip`() {
        val original = AddressDto(
            street = "Main Street",
            city = "Springfield",
            postcode = MaybeField(Maybe.Value("12345")),
        )

        val decoded = json.decodeFromString<AddressDto>(json.encodeToString(original))

        assertEquals(original.street, decoded.street)
        assertEquals(original.city, decoded.city)
        val decodedPostcode = decoded.postcode.value as Maybe.Value<*>
        assertEquals("12345", (decodedPostcode.v as JsonPrimitive).content)
    }

    // postcode: string? in the .emi.yml -> MaybeField<String> defaulting to
    // MaybeField(Maybe.Absent) when not supplied, so callers don't have to spell out
    // every optional field.
    @Test
    fun `optional fields default to absent`() {
        val address = AddressDto(street = "Main Street", city = "Springfield")

        assertEquals(Maybe.Absent, address.postcode.value)
    }

    // TeamDto is entity-derived (see the `team` entity in definitions.emi.yml); its
    // only non-generated field is `title`, plus the uniqueId every entity dto gets.
    // uniqueId is checked the same content-based way as AddressDto.postcode above.
    @Test
    fun `TeamDto round trips through JSON`() {
        val team = TeamDto(uniqueId = MaybeField(Maybe.Value("team-1")), title = "Rocketeers")

        val decoded = json.decodeFromString<TeamDto>(json.encodeToString(team))

        assertEquals("Rocketeers", decoded.title)
        val decodedUniqueId = decoded.uniqueId.value as Maybe.Value<*>
        assertEquals("team-1", (decodedUniqueId.v as JsonPrimitive).content)
    }

    // member.badges is `type: array`, which nests a MemberDtoBadges class - confirms
    // nested array-of-object fields generate a usable, independently constructible
    // class.
    @Test
    fun `nested array field class is independently constructible`() {
        val badge = MemberDtoBadges(label = "founder")

        assertEquals("founder", badge.label)
    }

    // Every hand-written action (buildProfile, lookupAddress) and every
    // entity-synthesized action (team/member create, get, update, browse) should
    // carry the name/url/method the .emi.yml describes.
    @Test
    fun `hand-written action metadata matches the emi definition`() {
        assertEquals(Triple("BuildProfileAction", "/profile/build", "post"),
            BuildProfileActionMeta().let { Triple(it.name, it.url, it.method) })

        assertEquals(Triple("LookupAddressAction", "/address/:postcode", "get"),
            LookupAddressActionMeta().let { Triple(it.name, it.url, it.method) })
    }

    @Test
    fun `entity-synthesized action metadata matches the emi definition`() {
        assertEquals(Triple("TeamCreateAction", "/team", "post"),
            TeamCreateActionMeta().let { Triple(it.name, it.url, it.method) })

        assertEquals(Triple("TeamGetAction", "/team/:uniqueId", "get"),
            TeamGetActionMeta().let { Triple(it.name, it.url, it.method) })

        assertEquals(Triple("TeamUpdateAction", "/team/:uniqueId", "patch"),
            TeamUpdateActionMeta().let { Triple(it.name, it.url, it.method) })

        assertEquals(Triple("MemberCreateAction", "/member", "post"),
            MemberCreateActionMeta().let { Triple(it.name, it.url, it.method) })

        assertEquals(Triple("MemberGetAction", "/member/:uniqueId", "get"),
            MemberGetActionMeta().let { Triple(it.name, it.url, it.method) })

        assertEquals(Triple("MemberBrowseAction", "/member/browse", "get"),
            MemberBrowseActionMeta().let { Triple(it.name, it.url, it.method) })
    }
}
