<?php

declare(strict_types=1);

// Generated by the Emi compiler - do not edit by hand.

namespace EmiSdk\Runtime;

/** Raised whenever the server answers with a non 2xx status code. */
class FetchxError extends \RuntimeException
{
    public function __construct(
        public readonly int $statusCode,
        public readonly mixed $payload
    ) {
        parent::__construct("request failed with status {$statusCode}");
    }
}
