<?php

declare(strict_types=1);

// Generated by the Emi compiler - do not edit by hand.

namespace EmiSdk\Runtime;

/**
 * Minimal runtime used by the generated Emi PHP client: builds urls,
 * performs HTTP requests through curl, and exposes a small helper to
 * consume Server-Sent Events for `method: reactive` actions.
 */
class Fetchx
{
    public static function defaultContext(): FetchxContext
    {
        static $instance = null;
        if ($instance === null) {
            $instance = new FetchxContext();
        }
        return $instance;
    }

    /** Joins a base url with a (possibly already-parameterized) path,
     * collapsing duplicate slashes at the seam. */
    public static function buildUrl(string $baseUrl, string $templateUrl): string
    {
        if ($baseUrl === '') {
            return $templateUrl;
        }
        return rtrim($baseUrl, '/') . '/' . ltrim($templateUrl, '/');
    }

    private static function appendQuery(string $url, ?array $params): string
    {
        if (!$params) {
            return $url;
        }

        $pairs = [];
        foreach ($params as $key => $value) {
            if ($value === null) {
                continue;
            }
            if (is_array($value)) {
                foreach ($value as $item) {
                    $pairs[] = rawurlencode((string) $key) . '=' . rawurlencode((string) $item);
                }
            } else {
                $pairs[] = rawurlencode((string) $key) . '=' . rawurlencode((string) $value);
            }
        }

        if (!$pairs) {
            return $url;
        }
        $separator = str_contains($url, '?') ? '&' : '?';
        return $url . $separator . implode('&', $pairs);
    }

    /** @return resource|\CurlHandle */
    private static function buildCurlHandle(
        string $method,
        string $url,
        ?array $params,
        mixed $jsonBody,
        ?array $headers,
        ?FetchxContext $ctx
    ) {
        $context = $ctx ?? self::defaultContext();
        $fullUrl = self::appendQuery($url, $params);

        $ch = curl_init($fullUrl);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, strtoupper($method));
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HEADER, false);

        $mergedHeaders = array_merge($context->defaultHeaders, $headers ?? []);
        if ($jsonBody !== null) {
            curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($jsonBody));
            $mergedHeaders['Content-Type'] = 'application/json';
        }

        $headerLines = [];
        foreach ($mergedHeaders as $key => $value) {
            $headerLines[] = "{$key}: {$value}";
        }
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headerLines);

        return $ch;
    }

    /** Performs a single HTTP call and returns the raw response body (or
     * null for an empty body). Throws {@see FetchxError} on non 2xx
     * statuses. Deserialize the result yourself via {@see self::deserialize()}. */
    public static function request(
        string $method,
        string $url,
        ?array $params = null,
        mixed $jsonBody = null,
        ?array $headers = null,
        ?FetchxContext $ctx = null
    ): ?string {
        $ch = self::buildCurlHandle($method, $url, $params, $jsonBody, $headers, $ctx);
        $body = curl_exec($ch);

        if ($body === false) {
            $error = curl_error($ch);
            throw new \RuntimeException("request failed: {$error}");
        }

        $statusCode = (int) curl_getinfo($ch, CURLINFO_RESPONSE_CODE);

        if ($statusCode >= 400) {
            throw new FetchxError($statusCode, $body === '' ? null : $body);
        }

        return $body === '' ? null : $body;
    }

    /** Deserializes a raw JSON string (as returned by {@see self::request()})
     * into an instance of $class, using {@see Hydrator::fromArray()}. */
    public static function deserialize(?string $json, string $class): mixed
    {
        if ($json === null) {
            return null;
        }
        $decoded = json_decode($json, true);
        return Hydrator::fromArray($class, $decoded);
    }

    /**
     * Consumes a `method: reactive` (server-sent events) endpoint, yielding
     * one raw payload string per event.
     *
     * Implementation note: cURL's easy API only exposes incoming bytes
     * through a synchronous write callback, and a PHP generator can't
     * suspend from inside a nested callback back out to its own caller - so
     * this collects every event during the single, blocking `curl_exec`
     * call, then yields them. That's correct for any bounded stream, but a
     * caller only sees events once the connection closes, not as they
     * arrive - a long-lived/infinite stream would need a different
     * transport (e.g. curl_multi with polling) that this runtime doesn't
     * attempt.
     */
    public static function streamEvents(
        string $method,
        string $url,
        ?array $params = null,
        mixed $jsonBody = null,
        ?array $headers = null,
        ?FetchxContext $ctx = null
    ): \Generator {
        $ch = self::buildCurlHandle($method, $url, $params, $jsonBody, $headers, $ctx);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, false);

        $events = [];
        $dataLines = [];
        $buffer = '';

        $flush = function () use (&$dataLines, &$events): void {
            if ($dataLines) {
                $events[] = implode("\n", $dataLines);
                $dataLines = [];
            }
        };

        curl_setopt($ch, CURLOPT_WRITEFUNCTION, function ($curlHandle, string $chunk) use (&$buffer, &$dataLines, $flush): int {
            $buffer .= $chunk;
            while (($pos = strpos($buffer, "\n")) !== false) {
                $line = rtrim(substr($buffer, 0, $pos), "\r");
                $buffer = substr($buffer, $pos + 1);

                if ($line === '') {
                    $flush();
                    continue;
                }
                if (str_starts_with($line, 'data:')) {
                    $dataLines[] = ltrim(substr($line, 5));
                }
            }
            return strlen($chunk);
        });

        $ok = curl_exec($ch);

        // A final line with no trailing newline (the very end of the
        // response) never went through the callback's own line-splitting.
        if ($buffer !== '' && str_starts_with($buffer, 'data:')) {
            $dataLines[] = ltrim(substr($buffer, 5));
        }
        $flush();

        if ($ok === false) {
            $error = curl_error($ch);
            throw new \RuntimeException("request failed: {$error}");
        }

        $statusCode = (int) curl_getinfo($ch, CURLINFO_RESPONSE_CODE);

        if ($statusCode >= 400) {
            throw new FetchxError($statusCode, $events ? implode("\n", $events) : null);
        }

        foreach ($events as $event) {
            yield $event;
        }
    }
}
