<?php

declare(strict_types=1);

// Generated by the Emi compiler - do not edit by hand.

namespace EmiSdk\Runtime;

/**
 * Carries the base url + default headers for every generated action
 * method. Build one and pass it to every call, or rely on
 * {@see Fetchx::defaultContext()} for a single process-wide instance.
 */
class FetchxContext
{
    public string $baseUrl = '';
    public array $defaultHeaders = [];

    public function buildUrl(string $templateUrl): string
    {
        return Fetchx::buildUrl($this->baseUrl, $templateUrl);
    }
}
