<?php

declare(strict_types=1);

// Generated by the Emi compiler - do not edit by hand.

namespace EmiSdk\Runtime;

/**
 * Generic object <-> array (de)serialization used by every generated dto
 * and action, via PHP's own runtime reflection - the same role
 * lib/python's serialization.py plays, since PHP (like Python, unlike
 * Dart/Java/C#) has full reflection available at runtime and needs no
 * per-class (de)serialization code generated at all.
 */
final class Hydrator
{
    /** Recursively converts an object (or array/BackedEnum/scalar
     * containing them) into plain, JSON-safe values. */
    public static function toArray(mixed $value): mixed
    {
        if ($value === null) {
            return null;
        }
        if ($value instanceof \BackedEnum) {
            return $value->value;
        }
        if (is_array($value)) {
            $isList = array_is_list($value);
            $result = [];
            foreach ($value as $key => $item) {
                $result[$key] = self::toArray($item);
            }
            return $isList ? array_values($result) : $result;
        }
        if (is_object($value)) {
            $result = [];
            foreach (get_object_vars($value) as $key => $item) {
                $result[$key] = self::toArray($item);
            }
            return $result;
        }
        return $value;
    }

    /**
     * Recursively builds a `$class` instance out of a plain (already
     * `json_decode(..., true)`-d) array, recursing into nested
     * objects/enums based on each property's own declared type - and, for
     * `array`-typed properties (erased at runtime, since PHP has no
     * generics), the class's own static `$arrayItemTypes` map (see
     * lib/php/php-class-generator.go) when its elements need coercion to an
     * object/enum too. Unknown keys in `$data` are ignored; missing keys
     * fall back to the property's own default (including anything set up
     * in the class's constructor).
     */
    public static function fromArray(string $class, mixed $data): mixed
    {
        if ($data === null) {
            return null;
        }

        if (enum_exists($class)) {
            /** @var class-string<\BackedEnum> $class */
            return is_string($data) || is_int($data) ? ($class::tryFrom($data) ?? $class::cases()[0]) : null;
        }

        if (!class_exists($class) || !is_array($data)) {
            return $data;
        }

        $instance = new $class();
        $ref = new \ReflectionClass($class);

        /** @var array<string, class-string> $arrayItemTypes */
        $arrayItemTypes = property_exists($class, 'arrayItemTypes') ? $class::$arrayItemTypes : [];

        foreach ($ref->getProperties(\ReflectionProperty::IS_PUBLIC) as $prop) {
            if ($prop->isStatic()) {
                continue;
            }
            $name = $prop->getName();
            if (!array_key_exists($name, $data)) {
                continue;
            }

            $rawValue = $data[$name];
            $type = $prop->getType();

            if ($rawValue === null) {
                $prop->setValue($instance, null);
                continue;
            }

            if ($type instanceof \ReflectionNamedType && !$type->isBuiltin()) {
                $prop->setValue($instance, self::fromArray($type->getName(), $rawValue));
                continue;
            }

            if ($type instanceof \ReflectionNamedType && $type->getName() === 'array' && is_array($rawValue)) {
                $itemClass = $arrayItemTypes[$name] ?? null;
                if ($itemClass !== null) {
                    $coerced = [];
                    foreach ($rawValue as $key => $item) {
                        $coerced[$key] = self::fromArray($itemClass, $item);
                    }
                    $prop->setValue($instance, $coerced);
                    continue;
                }
            }

            $prop->setValue($instance, $rawValue);
        }

        return $instance;
    }
}
