// Minimal runtime used by the generated Emi C# client: builds urls, performs
// HTTP requests through System.Net.Http.HttpClient, and exposes a small
// helper to consume Server-Sent Events for `method: reactive` actions.
//
// Generated by the Emi compiler - do not edit by hand.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Net.Http;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

namespace EmiSdk;

/// <summary>Raised whenever the server answers with a non 2xx status code.</summary>
public class FetchxError : Exception
{
    public int StatusCode { get; }
    public string? Payload { get; }

    public FetchxError(int statusCode, string? payload)
        : base($"request failed with status {statusCode}")
    {
        StatusCode = statusCode;
        Payload = payload;
    }
}

/// <summary>
/// Carries the base url + default headers + an optional shared HttpClient
/// for every generated action method. Build one and pass it as `ctx:` to
/// every call, or rely on <see cref="Fetchx.DefaultContext"/> for a single
/// process-wide instance.
/// </summary>
public class FetchxContext
{
    public string BaseUrl { get; set; } = "";
    public Dictionary<string, string> DefaultHeaders { get; set; } = new();
    public HttpClient? Client { get; set; }

    public string BuildUrl(string templateUrl) => Fetchx.BuildUrl(BaseUrl, templateUrl);
}

public static class Fetchx
{
    /// <summary>A process-wide default context, mutated in place so
    /// generated action methods can be called without threading a context
    /// through every single call.</summary>
    public static readonly FetchxContext DefaultContext = new();

    /// <summary>Joins a base url with a (possibly already-parameterized)
    /// path, collapsing duplicate slashes at the seam.</summary>
    public static string BuildUrl(string baseUrl, string templateUrl)
    {
        if (string.IsNullOrEmpty(baseUrl)) return templateUrl;
        return baseUrl.TrimEnd('/') + "/" + templateUrl.TrimStart('/');
    }

    private static string AppendQuery(string url, IDictionary<string, object>? parameters)
    {
        if (parameters == null || parameters.Count == 0) return url;

        var pairs = new List<string>();
        foreach (var kv in parameters)
        {
            if (kv.Value == null) continue;
            if (kv.Value is IEnumerable enumerable && kv.Value is not string)
            {
                foreach (var item in enumerable)
                {
                    pairs.Add($"{Uri.EscapeDataString(kv.Key)}={Uri.EscapeDataString(item?.ToString() ?? "")}");
                }
            }
            else
            {
                pairs.Add($"{Uri.EscapeDataString(kv.Key)}={Uri.EscapeDataString(kv.Value.ToString() ?? "")}");
            }
        }

        if (pairs.Count == 0) return url;
        var separator = url.Contains('?') ? "&" : "?";
        return url + separator + string.Join("&", pairs);
    }

    private static HttpRequestMessage BuildRequest(
        string method,
        string url,
        IDictionary<string, object>? parameters,
        object? jsonBody,
        IDictionary<string, string>? headers,
        FetchxContext context)
    {
        var fullUrl = AppendQuery(url, parameters);
        var request = new HttpRequestMessage(new HttpMethod(method), fullUrl);

        foreach (var kv in context.DefaultHeaders)
        {
            request.Headers.TryAddWithoutValidation(kv.Key, kv.Value);
        }
        if (headers != null)
        {
            foreach (var kv in headers)
            {
                request.Headers.TryAddWithoutValidation(kv.Key, kv.Value);
            }
        }

        if (jsonBody != null)
        {
            var json = JsonSerializer.Serialize(jsonBody);
            request.Content = new StringContent(json, Encoding.UTF8, "application/json");
        }

        return request;
    }

    /// <summary>Performs a single HTTP call and returns the raw response
    /// body (or null for an empty body). Throws <see cref="FetchxError"/> on
    /// non 2xx statuses. Deserialize the result yourself, e.g. via
    /// `JsonSerializer.Deserialize&lt;T&gt;(result)`.</summary>
    public static async Task<string?> Request(
        string method,
        string url,
        IDictionary<string, object>? parameters = null,
        object? jsonBody = null,
        IDictionary<string, string>? headers = null,
        FetchxContext? ctx = null)
    {
        var context = ctx ?? DefaultContext;
        var client = context.Client ?? new HttpClient();
        var ownsClient = context.Client == null;

        try
        {
            var request = BuildRequest(method, url, parameters, jsonBody, headers, context);
            var response = await client.SendAsync(request);
            var body = await response.Content.ReadAsStringAsync();

            if ((int)response.StatusCode >= 400)
            {
                throw new FetchxError((int)response.StatusCode, body);
            }

            return string.IsNullOrEmpty(body) ? null : body;
        }
        finally
        {
            if (ownsClient) client.Dispose();
        }
    }

    /// <summary>Consumes a `method: reactive` (server-sent events) endpoint,
    /// yielding one raw payload string per event. Deserialize each yourself,
    /// e.g. via `JsonSerializer.Deserialize&lt;T&gt;(evt)`.</summary>
    public static async IAsyncEnumerable<string> StreamEvents(
        string method,
        string url,
        IDictionary<string, object>? parameters = null,
        object? jsonBody = null,
        IDictionary<string, string>? headers = null,
        FetchxContext? ctx = null,
        [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var context = ctx ?? DefaultContext;
        var client = context.Client ?? new HttpClient();
        var ownsClient = context.Client == null;

        try
        {
            var request = BuildRequest(method, url, parameters, jsonBody, headers, context);
            using var response = await client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, cancellationToken);

            if ((int)response.StatusCode >= 400)
            {
                var errBody = await response.Content.ReadAsStringAsync(cancellationToken);
                throw new FetchxError((int)response.StatusCode, errBody);
            }

            using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            using var reader = new System.IO.StreamReader(stream);

            var dataLines = new List<string>();
            while (true)
            {
                // `ReadLineAsync` returning null (rather than checking
                // `EndOfStream` first) is the analyzer-clean way to detect
                // end-of-stream in an async loop (CA2024).
                var line = await reader.ReadLineAsync(cancellationToken);
                if (line == null) break;

                if (line.Length == 0)
                {
                    if (dataLines.Count > 0)
                    {
                        yield return string.Join("\n", dataLines);
                        dataLines.Clear();
                    }
                    continue;
                }

                if (line.StartsWith("data:"))
                {
                    dataLines.Add(line.Substring(5).TrimStart());
                }
            }

            if (dataLines.Count > 0)
            {
                yield return string.Join("\n", dataLines);
            }
        }
        finally
        {
            if (ownsClient) client.Dispose();
        }
    }
}
