"""Emi runtime: request/streaming helpers (fetchx) and generic dataclass
(de)serialization (serialization), shared by every generated dto/action.

Generated by the Emi compiler - do not edit by hand.
"""
