"""
Minimal runtime used by the generated Emi python client: builds urls,
performs HTTP requests (sync and async) through httpx, and exposes a small
helper to consume Server-Sent Events for `method: reactive` actions.

Generated by the Emi compiler - do not edit by hand.
"""
from __future__ import annotations

import json as _json
from dataclasses import dataclass, field
from typing import Any, AsyncIterator, Dict, Iterator, List, Optional

import httpx


class FetchxError(Exception):
    """Raised whenever the server answers with a non 2xx status code."""

    def __init__(self, status_code: int, payload: Any, message: str = ""):
        super().__init__(message or f"request failed with status {status_code}")
        self.status_code = status_code
        self.payload = payload


@dataclass
class FetchxContext:
    """
    Carries the base url + default headers + an optional shared httpx client
    for every generated action function. Build one and pass it as `ctx=` to
    every call, or rely on `DEFAULT_CONTEXT` / `configure()` for a single
    process-wide instance.
    """

    base_url: str = ""
    default_headers: Dict[str, str] = field(default_factory=dict)
    client: Optional[httpx.Client] = None
    async_client: Optional[httpx.AsyncClient] = None
    timeout: float = 30.0

    def build_url(self, template_url: str) -> str:
        return build_url(self.base_url, template_url)


# A process-wide default context, mutated in place by `configure()` so
# generated action functions can be called without threading a context
# through every single call.
DEFAULT_CONTEXT = FetchxContext()


def configure(
    base_url: str = "",
    default_headers: Optional[Dict[str, str]] = None,
    timeout: float = 30.0,
) -> FetchxContext:
    """Configures the process-wide DEFAULT_CONTEXT in place, and returns it."""
    DEFAULT_CONTEXT.base_url = base_url
    DEFAULT_CONTEXT.default_headers = default_headers or {}
    DEFAULT_CONTEXT.timeout = timeout
    return DEFAULT_CONTEXT


def build_url(base_url: str, template_url: str) -> str:
    """Joins a base url with a (possibly already-parameterized) path,
    collapsing duplicate slashes at the seam."""
    if not base_url:
        return template_url
    return base_url.rstrip("/") + "/" + template_url.lstrip("/")


def _merged_headers(ctx: Optional[FetchxContext], headers: Optional[Dict[str, str]]) -> Dict[str, str]:
    merged: Dict[str, str] = {}
    if ctx is not None:
        merged.update(ctx.default_headers)
    if headers:
        merged.update(headers)
    return merged


def _raise_for_status(response: httpx.Response) -> None:
    if response.status_code >= 400:
        try:
            payload = response.json()
        except ValueError:
            payload = response.text
        raise FetchxError(response.status_code, payload)


def _parse_response(response: httpx.Response) -> Any:
    if not response.content:
        return None
    content_type = response.headers.get("content-type", "")
    if "application/json" in content_type:
        return response.json()
    return response.text


def request(
    method: str,
    url: str,
    *,
    params: Optional[Dict[str, Any]] = None,
    json_body: Any = None,
    headers: Optional[Dict[str, str]] = None,
    ctx: Optional[FetchxContext] = None,
) -> Any:
    """Performs a single, synchronous HTTP call and returns the parsed
    (json or text) response body. Raises FetchxError on non 2xx statuses."""
    ctx = ctx or DEFAULT_CONTEXT
    client = ctx.client
    owns_client = client is None
    if owns_client:
        client = httpx.Client(timeout=ctx.timeout)

    try:
        response = client.request(
            method,
            url,
            params=params,
            json=json_body,
            headers=_merged_headers(ctx, headers),
        )
        _raise_for_status(response)
        return _parse_response(response)
    finally:
        if owns_client:
            client.close()


async def request_async(
    method: str,
    url: str,
    *,
    params: Optional[Dict[str, Any]] = None,
    json_body: Any = None,
    headers: Optional[Dict[str, str]] = None,
    ctx: Optional[FetchxContext] = None,
) -> Any:
    """Async counterpart of `request`, used by client functions generated
    with the `async` tag."""
    ctx = ctx or DEFAULT_CONTEXT
    client = ctx.async_client
    owns_client = client is None
    if owns_client:
        client = httpx.AsyncClient(timeout=ctx.timeout)

    try:
        response = await client.request(
            method,
            url,
            params=params,
            json=json_body,
            headers=_merged_headers(ctx, headers),
        )
        _raise_for_status(response)
        return _parse_response(response)
    finally:
        if owns_client:
            await client.aclose()


def _iter_sse_events(lines: Iterator[str]) -> Iterator[Any]:
    data_lines: List[str] = []
    for raw_line in lines:
        line = raw_line.rstrip("\n")
        if line == "":
            if data_lines:
                payload = "\n".join(data_lines)
                data_lines = []
                try:
                    yield _json.loads(payload)
                except ValueError:
                    yield payload
            continue
        if line.startswith("data:"):
            data_lines.append(line[len("data:"):].lstrip())
    if data_lines:
        payload = "\n".join(data_lines)
        try:
            yield _json.loads(payload)
        except ValueError:
            yield payload


def stream_events(
    method: str,
    url: str,
    *,
    params: Optional[Dict[str, Any]] = None,
    json_body: Any = None,
    headers: Optional[Dict[str, str]] = None,
    ctx: Optional[FetchxContext] = None,
) -> Iterator[Any]:
    """Consumes a `method: reactive` (server-sent events) endpoint
    synchronously, yielding one parsed payload per event."""
    ctx = ctx or DEFAULT_CONTEXT
    with httpx.Client(timeout=None) as client:
        with client.stream(
            method,
            url,
            params=params,
            json=json_body,
            headers=_merged_headers(ctx, headers),
        ) as response:
            _raise_for_status(response)
            yield from _iter_sse_events(response.iter_lines())


async def stream_events_async(
    method: str,
    url: str,
    *,
    params: Optional[Dict[str, Any]] = None,
    json_body: Any = None,
    headers: Optional[Dict[str, str]] = None,
    ctx: Optional[FetchxContext] = None,
) -> AsyncIterator[Any]:
    """Async counterpart of `stream_events`."""
    ctx = ctx or DEFAULT_CONTEXT
    async with httpx.AsyncClient(timeout=None) as client:
        async with client.stream(
            method,
            url,
            params=params,
            json=json_body,
            headers=_merged_headers(ctx, headers),
        ) as response:
            _raise_for_status(response)
            data_lines: List[str] = []
            async for raw_line in response.aiter_lines():
                line = raw_line.rstrip("\n")
                if line == "":
                    if data_lines:
                        payload = "\n".join(data_lines)
                        data_lines = []
                        try:
                            yield _json.loads(payload)
                        except ValueError:
                            yield payload
                    continue
                if line.startswith("data:"):
                    data_lines.append(line[len("data:"):].lstrip())
