"""
Generic dataclass <-> dict (de)serialization used by every generated dto and
action. Kept intentionally small and dependency-free (stdlib only) - the
sibling generators lean on a library for this (kotlinx.serialization,
Codable); python doesn't ship an equivalent, so Emi generates this module
once and every dataclass reuses it instead of hand-rolling per-class
(de)serialization code.

Generated by the Emi compiler - do not edit by hand.
"""
from __future__ import annotations

import dataclasses
import enum
import typing
from typing import Any, Type, TypeVar

T = TypeVar("T")


def to_dict(obj: Any) -> Any:
    """Recursively converts a dataclass instance (or list/dict/enum/plain
    value containing them) into plain, JSON-safe python primitives."""
    if obj is None:
        return None
    if dataclasses.is_dataclass(obj) and not isinstance(obj, type):
        return {f.name: to_dict(getattr(obj, f.name)) for f in dataclasses.fields(obj)}
    if isinstance(obj, enum.Enum):
        return obj.value
    if isinstance(obj, (list, tuple)):
        return [to_dict(item) for item in obj]
    if isinstance(obj, dict):
        return {key: to_dict(value) for key, value in obj.items()}
    return obj


def _unwrap_optional(tp: Any) -> Any:
    origin = typing.get_origin(tp)
    if origin is typing.Union:
        args = [a for a in typing.get_args(tp) if a is not type(None)]
        if len(args) == 1:
            return args[0]
    return tp


def _build_value(tp: Any, value: Any) -> Any:
    if value is None:
        return None

    tp = _unwrap_optional(tp)
    origin = typing.get_origin(tp)

    if dataclasses.is_dataclass(tp):
        if isinstance(value, dict):
            return from_dict(tp, value)
        return value

    if origin is list or tp is list:
        args = typing.get_args(tp)
        item_type = args[0] if args else Any
        return [_build_value(item_type, item) for item in value]

    if origin is dict or tp is dict:
        args = typing.get_args(tp)
        value_type = args[1] if len(args) > 1 else Any
        return {key: _build_value(value_type, val) for key, val in value.items()}

    if isinstance(tp, type) and issubclass(tp, enum.Enum):
        try:
            return tp(value)
        except ValueError:
            return value

    return value


def from_dict(cls: Type[T], data: Any) -> T:
    """Recursively builds a `cls` dataclass instance out of a plain dict
    (typically straight out of `response.json()`), recursing into nested
    dataclasses/lists/dicts/enums based on the dataclass' own type hints.
    Unknown keys in `data` are ignored; missing keys fall back to the
    field's own default."""
    if data is None:
        return None  # type: ignore[return-value]

    if not dataclasses.is_dataclass(cls):
        return data

    if isinstance(data, cls):
        return data

    hints = typing.get_type_hints(cls)
    kwargs: dict = {}
    for f in dataclasses.fields(cls):
        if not isinstance(data, dict) or f.name not in data:
            continue
        field_type = hints.get(f.name, Any)
        kwargs[f.name] = _build_value(field_type, data[f.name])

    return cls(**kwargs)
