compile:
	echo "Compiling envelopes stopped, due to usage of the generics, which emi compiler doesn't support."
# 	rm -rf src/google-json-style-guide/generated && ../emi js:module --path src/google-json-style-guide/google-envelop.emi.yml --output src/google-json-style-guide/generated --tags typescript,no-envelope