// react-form-writer.go is the React half of Emi's form compiler (see
// lib/formgen for the renderer-agnostic half). Given a single EmiDto it
// produces one self-contained .tsx file:
//
//   - a root `{Dto}Form` component, controlled via `value`/`onChange` (no
//     internal state - the caller owns the data, same convention every field
//     down the tree uses);
//   - one sibling function *per nested object/array field* (WidgetObjectGroup/
//     WidgetArrayGroup) - never inlined into the parent, so the file stays
//     readable no matter how deep a dto nests;
//   - one JSX element per leaf field, using whatever component the active
//     formgen.Toolset configured for that field's WidgetKind (see
//     react-form-toolset.go).
//
// It deliberately assumes two things exist elsewhere and never generates
// them itself:
//  1. The primitive field widgets (TextField, NumberField, ...) - this
//     compiler only ever imports them, from --form-components.
//  2. `one`/`collection` relation fields point at another entity this
//     compiler was never given the fields of, so it imports a
//     `{Target}Picker` component from --form-relations instead of inlining
//     anything.
//
// This is a "generate and forget" writer: the whole file is rebuilt from
// scratch every run, there is no merge/patch step and no generated/manual
// region markers - regenerate it, don't hand-edit it.
package js

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/torabian/emi/lib/core"
	"github.com/torabian/emi/lib/formgen"
)

// ReactFormGenerator turns a single dto into its form .tsx VirtualFile.
func ReactFormGenerator(dto core.EmiDto, toolset formgen.Toolset) (core.VirtualFile, error) {
	if dto.Name == "" {
		return core.VirtualFile{}, fmt.Errorf("js:form: dto has no name")
	}

	plan := formgen.BuildFormPlan(dto.GetClassName(), dto.Fields)
	b := newReactFormBuilder(toolset)

	rootValueType := dto.GetClassName() + "Values"
	rootTypeBlock := b.renderValueType(rootValueType, plan.Fields)

	bodyLines := make([]string, 0, len(plan.Fields))
	for _, f := range plan.Fields {
		bodyLines = append(bodyLines, "      "+b.renderFieldUsage(f))
	}

	rootComponent := dto.GetClassName() + "Form"
	rootBlock := fmt.Sprintf(`export interface %sProps {
  value: %s;
  onChange: (next: %s) => void;
}

export function %s({ value, onChange }: %sProps) {
  return (
    <>
%s
    </>
  );
}

export default %s;`,
		rootComponent, rootValueType, rootValueType,
		rootComponent, rootComponent,
		strings.Join(bodyLines, "\n"),
		rootComponent,
	)

	var out strings.Builder
	out.WriteString(reactFormHeader(dto.Name, rootComponent))
	out.WriteString("\n\n")
	if imp := b.imports.render(); imp != "" {
		out.WriteString(imp)
		out.WriteString("\n\n")
	}
	out.WriteString(rootTypeBlock)
	out.WriteString("\n\n")
	for _, blk := range b.blocks {
		out.WriteString(blk)
		out.WriteString("\n\n")
	}
	out.WriteString(rootBlock)
	out.WriteString("\n")

	return core.VirtualFile{
		Name:         rootComponent,
		Extension:    ".tsx",
		ActualScript: FormatWithPrettier(out.String(), true),
	}, nil
}

func reactFormHeader(dtoName string, rootComponent string) string {
	return fmt.Sprintf(`// Code generated by Emi's form compiler (js:form) from the %q dto. DO NOT EDIT.
// This file is regenerated in full every run - wrap %s instead of editing it
// if a field needs custom behaviour.
//
// Assumes these already exist on the UI side and are never generated by this
// compiler: the primitive widgets (TextField, NumberField, CheckboxField,
// SelectField, ListField, MapField, JsonField) and any one/collection
// relation picker components imported below.`, dtoName, rootComponent)
}

// ==========================
// Builder
// ==========================

// reactFormBuilder walks a formgen.FormPlan and accumulates the pieces of the
// final file: the imports every emitted JSX element needed, and one
// type-alias+function block per nested object/array group, emitted
// children-first as they're discovered.
type reactFormBuilder struct {
	toolset formgen.Toolset
	imports *jsImportSet
	blocks  []string
}

func newReactFormBuilder(toolset formgen.Toolset) *reactFormBuilder {
	return &reactFormBuilder{toolset: toolset, imports: newJsImportSet()}
}

func (b *reactFormBuilder) renderValueType(name string, fields []*formgen.FieldPlan) string {
	lines := make([]string, 0, len(fields))
	for _, f := range fields {
		optional := ""
		if f.Nullable {
			optional = "?"
		}
		lines = append(lines, fmt.Sprintf("  %s%s: %s;", f.Name, optional, b.tsType(f)))
	}
	return fmt.Sprintf("export type %s = {\n%s\n};", name, strings.Join(lines, "\n"))
}

func (b *reactFormBuilder) tsType(f *formgen.FieldPlan) string {
	switch f.Widget {
	case formgen.WidgetText:
		return "string"
	case formgen.WidgetNumber:
		return "number"
	case formgen.WidgetCheckbox:
		return "boolean"
	case formgen.WidgetSelect:
		if len(f.EnumOptions) == 0 {
			return "string"
		}
		lits := make([]string, 0, len(f.EnumOptions))
		for _, o := range f.EnumOptions {
			lits = append(lits, strconv.Quote(o.Value))
		}
		return strings.Join(lits, " | ")
	case formgen.WidgetPrimitiveList:
		return TsPrimitive(f.Primitive) + "[]"
	case formgen.WidgetMap:
		return "Record<string, any>"
	case formgen.WidgetObjectGroup:
		return f.GroupName + "Values"
	case formgen.WidgetArrayGroup:
		return f.GroupName + "ItemValues[]"
	case formgen.WidgetOneRelation:
		// The referenced entity's shape belongs to whatever produced its
		// dto/entity, not to this dto's own form file - the picker component
		// owns it instead.
		return "any"
	case formgen.WidgetCollectionRelation:
		return "any[]"
	case formgen.WidgetJson:
		return "any"
	default:
		return "any"
	}
}

// renderFieldUsage returns the JSX element (or one-line component usage) for
// a single field, ensuring any group/relation dependency it needs is
// registered first.
func (b *reactFormBuilder) renderFieldUsage(f *formgen.FieldPlan) string {
	path := "value." + f.Name
	setNext := fmt.Sprintf(`(next) => onChange({ ...value, %s: next })`, f.Name)

	switch f.Widget {
	case formgen.WidgetObjectGroup:
		formComponent := b.ensureObjectGroup(f)
		fallback := path
		if f.Nullable {
			fallback = fmt.Sprintf("%s ?? {}", path)
		}
		return fmt.Sprintf(`<%s value={%s} onChange={%s} />`, formComponent, fallback, setNext)

	case formgen.WidgetArrayGroup:
		arrayFormComponent := b.ensureArrayGroup(f)
		return fmt.Sprintf(`<%s value={%s ?? []} onChange={%s} />`, arrayFormComponent, path, setNext)

	case formgen.WidgetOneRelation:
		component := b.registerRelation(f)
		return fmt.Sprintf(`<%s value={%s} onChange={%s} />`, component, path, setNext)

	case formgen.WidgetCollectionRelation:
		component := b.registerRelation(f)
		return fmt.Sprintf(`<%s multiple value={%s ?? []} onChange={%s} />`, component, path, setNext)

	default:
		return b.renderLeaf(f)
	}
}

func (b *reactFormBuilder) registerRelation(f *formgen.FieldPlan) string {
	component := b.toolset.RelationComponent(f.Target)
	b.imports.addNamed(b.toolset.RelationImportFrom(f.Target, f.Module), component)
	return component
}

// ensureObjectGroup lazily renders the `{GroupName}Values` type and
// `{GroupName}Form` function for a WidgetObjectGroup field the first (and
// only) time it's encountered, and returns the function's name.
func (b *reactFormBuilder) ensureObjectGroup(f *formgen.FieldPlan) string {
	valueType := f.GroupName + "Values"
	formComponent := f.GroupName + "Form"

	bodyLines := make([]string, 0, len(f.Children))
	for _, child := range f.Children {
		bodyLines = append(bodyLines, "      "+b.renderFieldUsage(child))
	}

	typeBlock := b.renderValueType(valueType, f.Children)
	fnBlock := fmt.Sprintf(`function %s({ value, onChange }: { value: %s; onChange: (next: %s) => void }) {
  return (
    <>
%s
    </>
  );
}`, formComponent, valueType, valueType, strings.Join(bodyLines, "\n"))

	b.blocks = append(b.blocks, typeBlock, fnBlock)
	return formComponent
}

// ensureArrayGroup lazily renders the per-item `{GroupName}ItemValues` type
// and `{GroupName}ItemForm` function (reusing the same field-list rendering
// an object group would), plus a `{GroupName}ArrayForm` wrapper that repeats
// it per item with add/remove controls. Returns the wrapper's name.
func (b *reactFormBuilder) ensureArrayGroup(f *formgen.FieldPlan) string {
	itemValueType := f.GroupName + "ItemValues"
	itemFormComponent := f.GroupName + "ItemForm"
	arrayFormComponent := f.GroupName + "ArrayForm"

	bodyLines := make([]string, 0, len(f.Children))
	for _, child := range f.Children {
		bodyLines = append(bodyLines, "      "+b.renderFieldUsage(child))
	}

	typeBlock := b.renderValueType(itemValueType, f.Children)
	itemFnBlock := fmt.Sprintf(`function %s({ value, onChange }: { value: %s; onChange: (next: %s) => void }) {
  return (
    <>
%s
    </>
  );
}`, itemFormComponent, itemValueType, itemValueType, strings.Join(bodyLines, "\n"))

	arrayFnBlock := fmt.Sprintf(`function %s({ value, onChange }: { value: %s[]; onChange: (next: %s[]) => void }) {
  const items = value ?? [];
  return (
    <div>
      {items.map((item, index) => (
        <div key={index}>
          <%s
            value={item}
            onChange={(next) => {
              const copy = items.slice();
              copy[index] = next;
              onChange(copy);
            }}
          />
          <button type="button" onClick={() => onChange(items.filter((_, i) => i !== index))}>
            Remove
          </button>
        </div>
      ))}
      <button type="button" onClick={() => onChange([...items, {} as %s])}>
        Add
      </button>
    </div>
  );
}`, arrayFormComponent, itemValueType, itemValueType, itemFormComponent, itemValueType)

	b.blocks = append(b.blocks, typeBlock, itemFnBlock, arrayFnBlock)
	return arrayFormComponent
}

// renderLeaf handles every field whose WidgetKind isn't a group/relation, by
// looking its concrete component up in the active Toolset.
func (b *reactFormBuilder) renderLeaf(f *formgen.FieldPlan) string {
	widget, ok := b.toolset.Resolve(f.Widget)
	if !ok {
		// The toolset in use never configured this widget kind - fall back to
		// JSON so the field stays editable instead of silently disappearing
		// from the form.
		if fallback, fallbackOk := b.toolset.Resolve(formgen.WidgetJson); fallbackOk {
			widget = fallback
		} else {
			widget = formgen.WidgetComponent{Component: "JsonField", ImportFrom: DefaultFormComponentsImport, Named: true}
		}
	}
	b.registerImport(widget)

	path := "value." + f.Name
	props := []string{
		"label=" + strconv.Quote(formgen.HumanizeLabel(f.Name)),
		fmt.Sprintf("value={%s}", path),
		fmt.Sprintf("onChange={(next) => onChange({ ...value, %s: next })}", f.Name),
	}
	if !f.Nullable {
		props = append(props, "required")
	}
	if f.Field != nil && f.Field.Description != "" {
		props = append(props, "help="+strconv.Quote(f.Field.Description))
	}

	switch f.Widget {
	case formgen.WidgetSelect:
		opts := make([]string, 0, len(f.EnumOptions))
		for _, o := range f.EnumOptions {
			opts = append(opts, fmt.Sprintf("{ value: %s, label: %s }", strconv.Quote(o.Value), strconv.Quote(o.Label)))
		}
		props = append(props, fmt.Sprintf("options={[%s]}", strings.Join(opts, ", ")))
	case formgen.WidgetPrimitiveList:
		props = append(props, "primitive="+strconv.Quote(f.Primitive))
	case formgen.WidgetMap:
		if f.MapKeyOf != "" {
			props = append(props, "keyType="+strconv.Quote(f.MapKeyOf))
		}
		if f.MapPairOf != "" {
			props = append(props, "valueType="+strconv.Quote(f.MapPairOf))
		}
	}

	return fmt.Sprintf("<%s %s />", widget.Component, strings.Join(props, " "))
}

func (b *reactFormBuilder) registerImport(w formgen.WidgetComponent) {
	if w.ImportFrom == "" {
		return
	}
	if w.Named {
		b.imports.addNamed(w.ImportFrom, w.Component)
	} else {
		b.imports.addDefault(w.ImportFrom, w.Component)
	}
}

// ==========================
// Import bookkeeping
// ==========================

// jsImportSet collects, per module path, the default and/or named imports a
// generated file needs, and renders them back out as a deduplicated,
// deterministically-ordered block of `import` statements.
type jsImportSet struct {
	named map[string]map[string]bool
	def   map[string]string
	order []string
}

func newJsImportSet() *jsImportSet {
	return &jsImportSet{named: map[string]map[string]bool{}, def: map[string]string{}}
}

func (s *jsImportSet) touch(module string) {
	_, okNamed := s.named[module]
	_, okDef := s.def[module]
	if !okNamed && !okDef {
		s.order = append(s.order, module)
	}
}

func (s *jsImportSet) addNamed(module, name string) {
	s.touch(module)
	if s.named[module] == nil {
		s.named[module] = map[string]bool{}
	}
	s.named[module][name] = true
}

func (s *jsImportSet) addDefault(module, name string) {
	s.touch(module)
	s.def[module] = name
}

func (s *jsImportSet) render() string {
	lines := make([]string, 0, len(s.order))
	for _, module := range s.order {
		parts := []string{}
		if def, ok := s.def[module]; ok {
			parts = append(parts, def)
		}
		if names, ok := s.named[module]; ok && len(names) > 0 {
			list := make([]string, 0, len(names))
			for n := range names {
				list = append(list, n)
			}
			sort.Strings(list)
			parts = append(parts, "{ "+strings.Join(list, ", ")+" }")
		}
		lines = append(lines, fmt.Sprintf("import %s from %s;", strings.Join(parts, ", "), strconv.Quote(module)))
	}
	return strings.Join(lines, "\n")
}
