// react-jsonschema-form-writer.go is the react-jsonschema-form (RJSF) half
// of Emi's form compiler, an alternative to react-form-writer.go's generated
// TSX: instead of emitting one bespoke component per dto, it emits *data* -
// a JSON Schema (lib/formgen's renderer-agnostic BuildJSONSchema) - and a
// single generic `<Form schema={...} />` renders any dto. Nested object/array
// fields need no sub-components at all here: JSON Schema already expresses
// them natively (`properties`, `items`), and RJSF's own ObjectField/ArrayField
// render them recursively - the "keep array/object forms separate"
// requirement that forced dedicated functions in the TSX writer simply
// doesn't apply to a schema-driven renderer.
//
// Deliberately does not also emit an RJSF uiSchema: what plain JSON Schema
// can't express - `one`/`collection` relation fields (this compiler was never
// given the target entity's fields) and `any`/`complex` fields (no fixed
// shape at all) - would need a uiSchema entry naming a custom RJSF field
// component this compiler has no way to know the host app actually has, so
// both are just left as an unconstrained `{}` schema (see
// lib/formgen/jsonschema.go) and RJSF's own default rendering for that,
// rather than this compiler guessing at a wiring convention on the host's
// behalf.
package js

import (
	"encoding/json"
	"errors"
	"fmt"

	"github.com/torabian/emi/lib/core"
	"github.com/torabian/emi/lib/formgen"
)

// ReactJsonSchemaFormGenerator turns a single dto into two files:
//   - {Dto}.schema.json - the JSON Schema (formgen.BuildJSONSchema)
//   - {Dto}Form.tsx      - a thin wrapper around @rjsf/core's <Form>, wired to
//     the schema above and controlled via the same value/onChange convention
//     react-form-writer.go's components use.
func ReactJsonSchemaFormGenerator(dto core.EmiDto) ([]core.VirtualFile, error) {
	if dto.Name == "" {
		return nil, errors.New("js:rjsf: dto has no name")
	}

	return ReactJsonSchemaFormGeneratorForFields(dto.GetClassName(), dto.Description, dto.Fields)
}

// ReactJsonSchemaFormGeneratorForFields is ReactJsonSchemaFormGenerator's
// underlying implementation, taking a class name and field list directly
// instead of a core.EmiDto. This is what lets a caller generate an RJSF form
// for something that was never an explicit `emi: dto` - most notably an
// action's inline request/response `fields:` (see JsModuleFullVirtualFiles in
// js-module.go, which uses this for every {Action}Req/{Action}Res shape
// alongside the module's own dto: entries), since those only ever exist as a
// bare []*core.EmiField, never wrapped in a core.EmiDto.
func ReactJsonSchemaFormGeneratorForFields(className, description string, fields []*core.EmiField) ([]core.VirtualFile, error) {
	if className == "" {
		return nil, errors.New("js:rjsf: className is empty")
	}

	schema := formgen.BuildJSONSchema(className, description, fields)
	schemaJSON, err := json.MarshalIndent(schema, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("js:rjsf: failed marshaling schema: %w", err)
	}

	wrapper := rjsfWrapperComponent(className)

	return []core.VirtualFile{
		{Name: className + ".schema", Extension: ".json", ActualScript: string(schemaJSON) + "\n"},
		{Name: className + "Form", Extension: ".tsx", ActualScript: FormatWithPrettier(wrapper, true)},
	}, nil
}

func rjsfWrapperComponent(className string) string {
	return fmt.Sprintf(`// Code generated by Emi's form compiler (js:rjsf) from the %q dto. DO NOT EDIT.
// This file is regenerated in full every run alongside %s.schema.json - wrap
// %sForm instead of editing either of the two.

import Form from "@rjsf/core";
import validator from "@rjsf/validator-ajv8";
import schema from "./%s.schema.json";

export interface %sFormProps {
  value: any;
  onChange: (next: any) => void;
}

export function %sForm({ value, onChange }: %sFormProps) {
  return (
    <Form
      schema={schema as any}
      validator={validator}
      formData={value}
      onChange={(e) => onChange(e.formData)}
    >
      <></>
    </Form>
  );
}

export default %sForm;
`,
		className,
		className,
		className,
		className,
		className,
		className, className,
		className,
	)
}
