// Represents a file generated by Go WASM
export interface VirtualFile {
  Name: string;
  MimeType: string;
  Location: string;
  ActualScript: string;
  Extension: string;
}

// Options passed to the Go generator
export interface MicroGenContext {
  Tags: string;
  Output: string;
}
