/*
 * Minimal runtime used by the generated Emi C client: builds urls, performs
 * HTTP requests through libcurl, and exposes a small helper to consume
 * Server-Sent Events for `method: reactive` actions.
 *
 * Header-only, `static inline` throughout (matching cJSON.h's own style),
 * so it's safe to #include from as many translation units as needed with
 * no separate .c file and no duplicate-symbol link errors. Link against
 * libcurl itself (`-lcurl`).
 *
 * Ownership convention used throughout this runtime and every generated
 * dto/action header: a `char*`/pointer-typed field or return value is owned
 * by whoever holds it, and must be released with the matching `_free`
 * (or plain `free()` for raw strings) - exactly the same convention the
 * generated `Type_free()` functions follow.
 *
 * Generated by the Emi compiler - do not edit by hand.
 */
#ifndef EMISDK_FETCHX_H
#define EMISDK_FETCHX_H

#include "cjson/cJSON.h"
#include <curl/curl.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>

/* ---- context: base url + default headers -------------------------------- */

typedef struct FetchxContext {
    char* base_url;                     /* owned; "" if unset */
    struct curl_slist* default_headers; /* owned linked list, may be NULL */
} FetchxContext;

static inline FetchxContext* FetchxContext_new(void) {
    FetchxContext* ctx = (FetchxContext*) malloc(sizeof(FetchxContext));
    ctx->base_url = strdup("");
    ctx->default_headers = NULL;
    return ctx;
}

static inline void FetchxContext_set_base_url(FetchxContext* ctx, const char* base_url) {
    if (!ctx) return;
    free(ctx->base_url);
    ctx->base_url = strdup(base_url ? base_url : "");
}

/* Takes ownership of `value` is NOT done here - `key`/`value` are copied
 * into the curl_slist entry, so the caller keeps owning what it passed in. */
static inline void FetchxContext_add_default_header(FetchxContext* ctx, const char* key, const char* value) {
    if (!ctx) return;
    size_t len = strlen(key) + 2 + strlen(value) + 1;
    char* line = (char*) malloc(len);
    snprintf(line, len, "%s: %s", key, value);
    ctx->default_headers = curl_slist_append(ctx->default_headers, line);
    free(line); /* curl_slist_append copies the string internally */
}

static inline void FetchxContext_free(FetchxContext* ctx) {
    if (!ctx) return;
    free(ctx->base_url);
    curl_slist_free_all(ctx->default_headers);
    free(ctx);
}

/* ---- url helpers ---------------------------------------------------------- */

/* Joins a base url with a (possibly already-parameterized) path, collapsing
 * duplicate slashes at the seam. Returns a newly allocated string - the
 * caller must free() it. */
static inline char* fetchx_build_url(const char* base_url, const char* template_url) {
    if (!base_url || base_url[0] == '\0') {
        return strdup(template_url);
    }
    size_t base_len = strlen(base_url);
    while (base_len > 0 && base_url[base_len - 1] == '/') {
        base_len--;
    }
    const char* path = template_url;
    while (*path == '/') {
        path++;
    }
    size_t total = base_len + 1 + strlen(path) + 1;
    char* out = (char*) malloc(total);
    memcpy(out, base_url, base_len);
    out[base_len] = '/';
    strcpy(out + base_len + 1, path);
    return out;
}

/* Replaces the first occurrence of `placeholder` in `url` with
 * `replacement`. Returns a newly allocated string - the caller must free()
 * it (`url` itself is never modified or freed). */
static inline char* fetchx_url_replace(const char* url, const char* placeholder, const char* replacement) {
    const char* pos = strstr(url, placeholder);
    if (!pos) {
        return strdup(url);
    }
    size_t prefix_len = (size_t) (pos - url);
    size_t placeholder_len = strlen(placeholder);
    size_t suffix_len = strlen(pos + placeholder_len);
    size_t replacement_len = strlen(replacement);
    char* out = (char*) malloc(prefix_len + replacement_len + suffix_len + 1);
    memcpy(out, url, prefix_len);
    memcpy(out + prefix_len, replacement, replacement_len);
    memcpy(out + prefix_len + replacement_len, pos + placeholder_len, suffix_len + 1);
    return out;
}

/* Percent-encodes `s` for safe use as a query string key/value. Returns a
 * newly allocated string - the caller must free() it. */
static inline char* fetchx_url_encode(const char* s) {
    CURL* curl = curl_easy_init();
    char* encoded = curl_easy_escape(curl, s, 0);
    char* out = strdup(encoded ? encoded : "");
    if (encoded) {
        curl_free(encoded);
    }
    curl_easy_cleanup(curl);
    return out;
}

/* Appends `key=value` to `url` (as the first `?param` or an additional
 * `&param`), url-encoding both. Returns a newly allocated string - the
 * caller must free() it (`url` itself is never modified or freed). */
static inline char* fetchx_url_append_query(const char* url, const char* key, const char* value) {
    char* enc_key = fetchx_url_encode(key);
    char* enc_value = fetchx_url_encode(value);
    bool has_query = strchr(url, '?') != NULL;
    size_t total = strlen(url) + 1 + strlen(enc_key) + 1 + strlen(enc_value) + 1;
    char* out = (char*) malloc(total);
    snprintf(out, total, "%s%c%s=%s", url, has_query ? '&' : '?', enc_key, enc_value);
    free(enc_key);
    free(enc_value);
    return out;
}

/* ---- request/response ------------------------------------------------------ */

typedef struct FetchxResponse {
    long status_code;
    char* body;          /* owned, may be NULL (empty body, or on transport failure) */
    bool ok;              /* false on a transport-level failure (see error_message) */
    char* error_message; /* owned, set only when !ok */
} FetchxResponse;

static inline void FetchxResponse_free(FetchxResponse* res) {
    if (!res) {
        return;
    }
    free(res->body);
    res->body = NULL;
    free(res->error_message);
    res->error_message = NULL;
}

typedef struct fetchx_buffer_ {
    char* data;
    size_t size;
} fetchx_buffer_;

static inline size_t fetchx_write_cb_(void* contents, size_t size, size_t nmemb, void* userp) {
    size_t real_size = size * nmemb;
    fetchx_buffer_* buf = (fetchx_buffer_*) userp;
    char* ptr = (char*) realloc(buf->data, buf->size + real_size + 1);
    if (!ptr) {
        return 0;
    }
    buf->data = ptr;
    memcpy(&(buf->data[buf->size]), contents, real_size);
    buf->size += real_size;
    buf->data[buf->size] = '\0';
    return real_size;
}

/* Performs a single HTTP call. `headers` (if non-NULL) is merged with
 * `ctx`'s default headers - both remain owned by the caller, this function
 * never frees them. `json_body` (if non-NULL) is sent as the request body
 * with `Content-Type: application/json` added automatically. Always
 * returns a response - check `.ok` before trusting `.status_code`/`.body`,
 * and always release it with FetchxResponse_free() when done. */
static inline FetchxResponse fetchx_request(
    const char* method,
    const char* url,
    const char* json_body,
    struct curl_slist* headers,
    const FetchxContext* ctx
) {
    FetchxResponse response;
    memset(&response, 0, sizeof(response));

    CURL* curl = curl_easy_init();
    fetchx_buffer_ buf;
    buf.data = (char*) malloc(1);
    buf.data[0] = '\0';
    buf.size = 0;

    curl_easy_setopt(curl, CURLOPT_URL, url);
    curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, method);
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, fetchx_write_cb_);
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, (void*) &buf);

    struct curl_slist* all_headers = NULL;
    if (ctx) {
        for (struct curl_slist* h = ctx->default_headers; h; h = h->next) {
            all_headers = curl_slist_append(all_headers, h->data);
        }
    }
    for (struct curl_slist* h = headers; h; h = h->next) {
        all_headers = curl_slist_append(all_headers, h->data);
    }
    if (json_body) {
        all_headers = curl_slist_append(all_headers, "Content-Type: application/json");
        curl_easy_setopt(curl, CURLOPT_POSTFIELDS, json_body);
    }
    curl_easy_setopt(curl, CURLOPT_HTTPHEADER, all_headers);

    CURLcode result = curl_easy_perform(curl);
    if (result != CURLE_OK) {
        response.ok = false;
        response.error_message = strdup(curl_easy_strerror(result));
        free(buf.data);
    } else {
        long status = 0;
        curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &status);
        response.status_code = status;
        response.body = buf.data; /* ownership transferred to the response */
        response.ok = status < 400;
    }

    curl_slist_free_all(all_headers);
    curl_easy_cleanup(curl);
    return response;
}

/* ---- reactive (server-sent events) ---------------------------------------- */

typedef struct FetchxEventList {
    char** events; /* owned array of owned strings, one raw JSON payload per event */
    size_t count;
} FetchxEventList;

static inline void FetchxEventList_free(FetchxEventList* list) {
    if (!list) {
        return;
    }
    for (size_t i = 0; i < list->count; i++) {
        free(list->events[i]);
    }
    free(list->events);
    list->events = NULL;
    list->count = 0;
}

static inline void fetchx_events_push_(FetchxEventList* list, size_t* capacity, const char* data, size_t len) {
    if (list->count == *capacity) {
        *capacity = *capacity ? *capacity * 2 : 4;
        list->events = (char**) realloc(list->events, *capacity * sizeof(char*));
    }
    char* copy = (char*) malloc(len + 1);
    memcpy(copy, data, len);
    copy[len] = '\0';
    list->events[list->count++] = copy;
}

/* Parses a full SSE (`text/event-stream`) response body into one entry per
 * event (only `data:` lines are collected; multi-line `data:` blocks within
 * one event are newline-joined, matching every sibling generator's
 * runtime). */
static inline FetchxEventList fetchx_parse_sse(const char* body) {
    FetchxEventList list;
    list.events = NULL;
    list.count = 0;
    size_t capacity = 0;
    if (!body) {
        return list;
    }

    char* data_buf = NULL;
    size_t data_len = 0;
    const char* line_start = body;

    while (*line_start) {
        const char* line_end = strchr(line_start, '\n');
        size_t line_len = line_end ? (size_t) (line_end - line_start) : strlen(line_start);
        size_t trimmed = line_len;
        if (trimmed > 0 && line_start[trimmed - 1] == '\r') {
            trimmed--;
        }

        if (trimmed == 0) {
            if (data_len > 0) {
                fetchx_events_push_(&list, &capacity, data_buf, data_len);
                free(data_buf);
                data_buf = NULL;
                data_len = 0;
            }
        } else if (trimmed >= 5 && strncmp(line_start, "data:", 5) == 0) {
            const char* value = line_start + 5;
            size_t value_len = trimmed - 5;
            while (value_len > 0 && *value == ' ') {
                value++;
                value_len--;
            }
            size_t sep = data_len > 0 ? 1 : 0;
            char* new_buf = (char*) malloc(data_len + sep + value_len + 1);
            size_t offset = 0;
            if (data_buf) {
                memcpy(new_buf, data_buf, data_len);
                offset = data_len;
                if (sep) {
                    new_buf[offset++] = '\n';
                }
            }
            memcpy(new_buf + offset, value, value_len);
            new_buf[offset + value_len] = '\0';
            free(data_buf);
            data_buf = new_buf;
            data_len = offset + value_len;
        }

        if (!line_end) {
            break;
        }
        line_start = line_end + 1;
    }

    if (data_len > 0) {
        fetchx_events_push_(&list, &capacity, data_buf, data_len);
        free(data_buf);
    }

    return list;
}

/* Consumes a `method: reactive` endpoint and returns every event it sent.
 *
 * Implementation note: libcurl's easy API only exposes incoming bytes
 * through a synchronous write callback (see fetchx_write_cb_), and C has no
 * generator/coroutine to suspend out of one - so this performs the whole
 * (blocking) request first via fetchx_request(), then parses every event
 * out of the complete body. That's correct for any bounded stream, but it
 * means a caller only sees events once the connection closes, not as they
 * arrive - a long-lived/infinite stream would need a different transport
 * (e.g. curl_multi with polling) that this runtime doesn't attempt. If
 * `out_response` is non-NULL, ownership of the underlying FetchxResponse is
 * transferred to the caller (release it with FetchxResponse_free);
 * otherwise it's released internally.
 */
static inline FetchxEventList fetchx_stream_events(
    const char* method,
    const char* url,
    const char* json_body,
    struct curl_slist* headers,
    const FetchxContext* ctx,
    FetchxResponse* out_response
) {
    FetchxResponse response = fetchx_request(method, url, json_body, headers, ctx);
    FetchxEventList list;
    list.events = NULL;
    list.count = 0;

    if (response.ok) {
        list = fetchx_parse_sse(response.body);
    }

    if (out_response) {
        *out_response = response;
    } else {
        FetchxResponse_free(&response);
    }
    return list;
}

#endif /* EMISDK_FETCHX_H */
