/// Minimal runtime used by the generated Emi dart client: builds urls,
/// performs HTTP requests through package:http, and exposes a small
/// helper to consume Server-Sent Events for `method: reactive` actions.
///
/// Generated by the Emi compiler - do not edit by hand.
library;

import 'dart:async';
import 'dart:convert';

import 'package:http/http.dart' as http;

/// Raised whenever the server answers with a non 2xx status code.
class FetchxError implements Exception {
  final int statusCode;
  final dynamic payload;

  FetchxError(this.statusCode, this.payload);

  @override
  String toString() => 'FetchxError($statusCode): $payload';
}

/// Carries the base url + default headers + an optional shared http.Client
/// for every generated action function. Build one and pass it as `ctx:` to
/// every call, or rely on `defaultContext` / `configure()` for a single
/// process-wide instance.
class FetchxContext {
  String baseUrl;
  Map<String, String> defaultHeaders;
  http.Client? client;

  FetchxContext({this.baseUrl = '', Map<String, String>? defaultHeaders, this.client})
      : defaultHeaders = defaultHeaders ?? <String, String>{};

  String buildUrl(String templateUrl) => buildUrlWith(baseUrl, templateUrl);
}

/// A process-wide default context, mutated in place by `configure()` so
/// generated action functions can be called without threading a context
/// through every single call.
final FetchxContext defaultContext = FetchxContext();

/// Configures the process-wide [defaultContext] in place, and returns it.
FetchxContext configure({String baseUrl = '', Map<String, String>? defaultHeaders}) {
  defaultContext.baseUrl = baseUrl;
  defaultContext.defaultHeaders = defaultHeaders ?? <String, String>{};
  return defaultContext;
}

/// Joins a base url with a (possibly already-parameterized) path, collapsing
/// duplicate slashes at the seam.
String buildUrlWith(String baseUrl, String templateUrl) {
  if (baseUrl.isEmpty) return templateUrl;
  final trimmedBase = baseUrl.replaceAll(RegExp(r'/+$'), '');
  final trimmedPath = templateUrl.replaceAll(RegExp(r'^/+'), '');
  return '$trimmedBase/$trimmedPath';
}

String _appendQuery(String url, Map<String, dynamic>? params) {
  if (params == null || params.isEmpty) return url;

  // Uri's `queryParameters` accepts either a String or an Iterable<String>
  // per key (the latter renders as repeated `key=a&key=b` pairs), so a
  // uniform `List<String>` value works for both single- and multi-valued
  // params.
  final queryAll = <String, List<String>>{};
  params.forEach((key, value) {
    if (value == null) return;
    if (value is List) {
      queryAll[key] = value.map((e) => e.toString()).toList();
    } else {
      queryAll[key] = [value.toString()];
    }
  });

  final queryString = Uri(queryParameters: queryAll).query;
  if (queryString.isEmpty) return url;

  final separator = url.contains('?') ? '&' : '?';
  return '$url$separator$queryString';
}

Map<String, String> _mergedHeaders(FetchxContext? ctx, Map<String, String>? headers) {
  final result = <String, String>{};
  if (ctx != null) result.addAll(ctx.defaultHeaders);
  if (headers != null) result.addAll(headers);
  return result;
}

http.Request _buildRequest(
  String method,
  String url, {
  Map<String, dynamic>? params,
  dynamic jsonBody,
  Map<String, String>? headers,
  FetchxContext? ctx,
}) {
  final fullUrl = _appendQuery(url, params);
  final req = http.Request(method, Uri.parse(fullUrl));
  req.headers.addAll(_mergedHeaders(ctx, headers));
  if (jsonBody != null) {
    req.headers['Content-Type'] = 'application/json';
    req.body = jsonEncode(jsonBody);
  }
  return req;
}

dynamic _parseBody(String body, Map<String, String> responseHeaders) {
  if (body.isEmpty) return null;
  final contentType = responseHeaders['content-type'] ?? '';
  if (contentType.contains('application/json')) {
    return jsonDecode(body);
  }
  return body;
}

/// Performs a single HTTP call and returns the parsed (json or text) response
/// body. Throws [FetchxError] on non 2xx statuses.
Future<dynamic> request(
  String method,
  String url, {
  Map<String, dynamic>? params,
  dynamic jsonBody,
  Map<String, String>? headers,
  FetchxContext? ctx,
}) async {
  final context = ctx ?? defaultContext;
  final client = context.client ?? http.Client();
  final ownsClient = context.client == null;

  try {
    final req = _buildRequest(method, url, params: params, jsonBody: jsonBody, headers: headers, ctx: ctx);
    final streamed = await client.send(req);
    final response = await http.Response.fromStream(streamed);

    if (response.statusCode >= 400) {
      dynamic payload;
      try {
        payload = jsonDecode(response.body);
      } catch (_) {
        payload = response.body;
      }
      throw FetchxError(response.statusCode, payload);
    }

    return _parseBody(response.body, response.headers);
  } finally {
    if (ownsClient) client.close();
  }
}

/// Consumes a `method: reactive` (server-sent events) endpoint, yielding one
/// parsed payload per event.
Stream<dynamic> streamEvents(
  String method,
  String url, {
  Map<String, dynamic>? params,
  dynamic jsonBody,
  Map<String, String>? headers,
  FetchxContext? ctx,
}) async* {
  final context = ctx ?? defaultContext;
  final client = context.client ?? http.Client();
  final ownsClient = context.client == null;

  try {
    final req = _buildRequest(method, url, params: params, jsonBody: jsonBody, headers: headers, ctx: ctx);
    final streamed = await client.send(req);

    if (streamed.statusCode >= 400) {
      final body = await streamed.stream.bytesToString();
      dynamic payload;
      try {
        payload = jsonDecode(body);
      } catch (_) {
        payload = body;
      }
      throw FetchxError(streamed.statusCode, payload);
    }

    final lines = streamed.stream.transform(utf8.decoder).transform(const LineSplitter());
    final dataLines = <String>[];

    await for (final rawLine in lines) {
      if (rawLine.isEmpty) {
        if (dataLines.isNotEmpty) {
          final payload = dataLines.join('\n');
          dataLines.clear();
          try {
            yield jsonDecode(payload);
          } catch (_) {
            yield payload;
          }
        }
        continue;
      }
      if (rawLine.startsWith('data:')) {
        dataLines.add(rawLine.substring(5).trimLeft());
      }
    }

    if (dataLines.isNotEmpty) {
      final payload = dataLines.join('\n');
      try {
        yield jsonDecode(payload);
      } catch (_) {
        yield payload;
      }
    }
  } finally {
    if (ownsClient) client.close();
  }
}
