package emisdk;

import java.net.http.HttpClient;
import java.util.HashMap;
import java.util.Map;

/**
 * Carries the base url + default headers + an optional shared HttpClient for
 * every generated action method. Build one and pass it to every call, or
 * rely on {@link Fetchx#DEFAULT_CONTEXT} for a single process-wide instance.
 *
 * Generated by the Emi compiler - do not edit by hand.
 */
public class FetchxContext {
    public String baseUrl = "";
    public Map<String, String> defaultHeaders = new HashMap<>();
    public HttpClient client;

    public String buildUrl(String templateUrl) {
        return Fetchx.buildUrl(baseUrl, templateUrl);
    }
}
