package emisdk;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Minimal runtime used by the generated Emi Java client: builds urls,
 * performs HTTP requests through java.net.http.HttpClient, and exposes a
 * small helper to consume Server-Sent Events for `method: reactive` actions.
 *
 * Generated by the Emi compiler - do not edit by hand.
 */
public class Fetchx {
    /** A process-wide default context, mutated in place so generated action
     * methods can be called without threading a context through every
     * single call. */
    public static final FetchxContext DEFAULT_CONTEXT = new FetchxContext();

    /** Shared Jackson mapper used both by this runtime (serializing request
     * bodies) and by generated action methods (deserializing responses via
     * {@link #deserialize}). FAIL_ON_EMPTY_BEANS is off because a field with
     * no `fields:` at all (an intentionally empty nested object) generates a
     * real, valid, property-less class - Jackson's default of treating that
     * as an error would be wrong here. */
    public static final ObjectMapper MAPPER = new ObjectMapper()
            .disable(com.fasterxml.jackson.databind.SerializationFeature.FAIL_ON_EMPTY_BEANS);

    /** Joins a base url with a (possibly already-parameterized) path,
     * collapsing duplicate slashes at the seam. */
    public static String buildUrl(String baseUrl, String templateUrl) {
        if (baseUrl == null || baseUrl.isEmpty()) return templateUrl;
        var trimmedBase = baseUrl.replaceAll("/+$", "");
        var trimmedPath = templateUrl.replaceAll("^/+", "");
        return trimmedBase + "/" + trimmedPath;
    }

    private static String urlEncode(String s) {
        return URLEncoder.encode(s, StandardCharsets.UTF_8);
    }

    private static String appendQuery(String url, Map<String, Object> params) {
        if (params == null || params.isEmpty()) return url;

        var pairs = new ArrayList<String>();
        for (var entry : params.entrySet()) {
            if (entry.getValue() == null) continue;
            if (entry.getValue() instanceof Iterable<?> iterable) {
                for (var item : iterable) {
                    pairs.add(urlEncode(entry.getKey()) + "=" + urlEncode(String.valueOf(item)));
                }
            } else {
                pairs.add(urlEncode(entry.getKey()) + "=" + urlEncode(String.valueOf(entry.getValue())));
            }
        }

        if (pairs.isEmpty()) return url;
        var separator = url.contains("?") ? "&" : "?";
        return url + separator + String.join("&", pairs);
    }

    private static HttpClient clientFor(FetchxContext ctx) {
        return ctx.client != null ? ctx.client : HttpClient.newHttpClient();
    }

    private static HttpRequest buildRequest(
            String method,
            String url,
            Map<String, Object> params,
            Object jsonBody,
            Map<String, String> headers,
            FetchxContext ctx) {
        var fullUrl = appendQuery(url, params);
        var builder = HttpRequest.newBuilder(URI.create(fullUrl));

        for (var entry : ctx.defaultHeaders.entrySet()) {
            builder.header(entry.getKey(), entry.getValue());
        }
        if (headers != null) {
            for (var entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }

        HttpRequest.BodyPublisher body = HttpRequest.BodyPublishers.noBody();
        if (jsonBody != null) {
            try {
                body = HttpRequest.BodyPublishers.ofString(MAPPER.writeValueAsString(jsonBody));
                builder.header("Content-Type", "application/json");
            } catch (JsonProcessingException e) {
                throw new RuntimeException(e);
            }
        }

        builder.method(method, body);
        return builder.build();
    }

    /** Performs a single HTTP call and returns the raw response body (or
     * null for an empty body). Throws {@link FetchxError} on non 2xx
     * statuses. Deserialize the result yourself via {@link #deserialize}. */
    public static String request(
            String method,
            String url,
            Map<String, Object> params,
            Object jsonBody,
            Map<String, String> headers,
            FetchxContext ctx) {
        var context = ctx != null ? ctx : DEFAULT_CONTEXT;
        var client = clientFor(context);
        var request = buildRequest(method, url, params, jsonBody, headers, context);

        try {
            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
            if (response.statusCode() >= 400) {
                throw new FetchxError(response.statusCode(), response.body());
            }
            return response.body() == null || response.body().isEmpty() ? null : response.body();
        } catch (IOException | InterruptedException e) {
            throw new RuntimeException(e);
        }
    }

    /** Deserializes a raw JSON string (as returned by {@link #request}) into
     * the given type, using the shared {@link #MAPPER}. */
    public static <T> T deserialize(String json, Class<T> type) {
        if (json == null) return null;
        try {
            return MAPPER.readValue(json, type);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    /** Consumes a `method: reactive` (server-sent events) endpoint,
     * returning an iterator of raw payload strings, one per event.
     * Deserialize each yourself via {@link #deserialize}. */
    public static Iterator<String> streamEvents(
            String method,
            String url,
            Map<String, Object> params,
            Object jsonBody,
            Map<String, String> headers,
            FetchxContext ctx) {
        var context = ctx != null ? ctx : DEFAULT_CONTEXT;
        var client = clientFor(context);
        var request = buildRequest(method, url, params, jsonBody, headers, context);

        try {
            HttpResponse<Stream<String>> response = client.send(request, HttpResponse.BodyHandlers.ofLines());
            if (response.statusCode() >= 400) {
                var body = response.body().collect(Collectors.joining("\n"));
                throw new FetchxError(response.statusCode(), body);
            }
            return new SseEventIterator(response.body().iterator());
        } catch (IOException | InterruptedException e) {
            throw new RuntimeException(e);
        }
    }

    private static class SseEventIterator implements Iterator<String> {
        private final Iterator<String> lines;
        private String next;

        SseEventIterator(Iterator<String> lines) {
            this.lines = lines;
            advance();
        }

        private void advance() {
            var dataLines = new ArrayList<String>();
            while (lines.hasNext()) {
                var line = lines.next();
                if (line.isEmpty()) {
                    if (!dataLines.isEmpty()) {
                        next = String.join("\n", dataLines);
                        return;
                    }
                    continue;
                }
                if (line.startsWith("data:")) {
                    dataLines.add(line.substring(5).stripLeading());
                }
            }
            next = dataLines.isEmpty() ? null : String.join("\n", dataLines);
        }

        @Override
        public boolean hasNext() {
            return next != null;
        }

        @Override
        public String next() {
            var value = next;
            advance();
            return value;
        }
    }
}
