package emisdk;

/**
 * Raised whenever the server answers with a non 2xx status code.
 *
 * Generated by the Emi compiler - do not edit by hand.
 */
public class FetchxError extends RuntimeException {
    public final int statusCode;
    public final String payload;

    public FetchxError(int statusCode, String payload) {
        super("request failed with status " + statusCode);
        this.statusCode = statusCode;
        this.payload = payload;
    }
}
