package cpp

import (
	"fmt"
	"slices"
	"strings"

	"github.com/torabian/emi/lib/core"
	cppIncludeGeneric "github.com/torabian/emi/lib/cpp/cpp-include/generic"
	cppIncludeUnreal "github.com/torabian/emi/lib/cpp/cpp-include/unreal"
)

// ---- generic dialect: common includes + `#pragma once` wrapping -------------

// An unused #include is never a compiler error in C++, so a single fixed set -
// covering every runtime header any generated dto/action file might need,
// including the ones only an action (never a plain dto) actually uses - is
// simpler and just as correct as computing a precise one per file (same
// reasoning the C target's own commonIncludes documents).
var cppGenericCommonIncludes = []string{
	`"cjson/cJSON.h"`,
	`"EmiJson.hpp"`,
	`"EmiHttpTransport.hpp"`,
	`"EmiByteStream.hpp"`,
	`"EmiWebSocketX.hpp"`,
	"<cstdint>",
	"<map>",
	"<memory>",
	"<optional>",
	"<string>",
	"<utility>",
	"<vector>",
}

// CppGenericAsFullDocument wraps a compiled chunk into a standalone,
// `#pragma once`-guarded .hpp file: the common includes, plus any module-specific
// #include (a sibling generated header, or a resolved complex type's own
// header), then the actual body.
func CppGenericAsFullDocument(x *core.CodeChunkCompiled) string {
	includes := make([]string, len(cppGenericCommonIncludes))
	copy(includes, cppGenericCommonIncludes)
	seen := map[string]struct{}{}
	for _, i := range includes {
		seen[i] = struct{}{}
	}
	for _, dep := range x.CodeChunkDependensies {
		if dep.Location == "" {
			continue
		}
		spelling := dep.Location
		if !strings.HasPrefix(spelling, "<") && !strings.HasPrefix(spelling, `"`) {
			spelling = `"` + spelling + `"`
		}
		if _, ok := seen[spelling]; ok {
			continue
		}
		seen[spelling] = struct{}{}
		includes = append(includes, spelling)
	}

	var sb strings.Builder
	sb.WriteString("// Generated by the Emi compiler - do not edit by hand.\n#pragma once\n\n")
	for _, i := range includes {
		fmt.Fprintf(&sb, "#include %v\n", i)
	}
	sb.WriteString("\n")
	sb.Write(x.ActualScript)

	return string(core.EscapeLines([]byte(sb.String())))
}

// ---- unreal dialect: `#pragma once` + CoreMinimal + trailing .generated.h ---

var cppUnrealCommonIncludes = []string{
	`"CoreMinimal.h"`,
	`"Dom/JsonValue.h"`,
}

// CppUnrealAsFullDocument wraps a compiled chunk into a standalone Unreal header:
// `#pragma once`, CoreMinimal.h + any module-specific #include, the actual body,
// and - critically, and always LAST, per Unreal Header Tool's own requirement -
// `#include "<FileName>.generated.h"`.
func CppUnrealAsFullDocument(x *core.CodeChunkCompiled, fileName string) string {
	includes := make([]string, len(cppUnrealCommonIncludes))
	copy(includes, cppUnrealCommonIncludes)
	seen := map[string]struct{}{}
	for _, i := range includes {
		seen[i] = struct{}{}
	}
	for _, dep := range x.CodeChunkDependensies {
		if dep.Location == "" {
			continue
		}
		spelling := dep.Location
		if !strings.HasPrefix(spelling, "<") && !strings.HasPrefix(spelling, `"`) {
			spelling = `"` + spelling + `"`
		}
		if _, ok := seen[spelling]; ok {
			continue
		}
		seen[spelling] = struct{}{}
		includes = append(includes, spelling)
	}

	var sb strings.Builder
	sb.WriteString("// Generated by the Emi compiler - do not edit by hand.\n#pragma once\n\n")
	for _, i := range includes {
		fmt.Fprintf(&sb, "#include %v\n", i)
	}
	sb.WriteString("\n")
	sb.Write(x.ActualScript)
	fmt.Fprintf(&sb, "\n#include %q\n", fileName+".generated.h")

	return string(core.EscapeLines([]byte(sb.String())))
}

// DiscoverComplexes finds every module-level complex type compiled for this
// dialect, mirroring the same helper in the sibling generators. ImportLocation is
// a #include spelling (generic) or an Unreal header name (unreal).
func DiscoverComplexes(module *core.Emi, dialect Dialect) []RecognizedComplex {
	want := map[Dialect][]string{
		DialectGeneric: {"cpp", "cpp-generic", ""},
		DialectUnreal:  {"cpp", "cpp-unreal", "unreal", ""},
	}[dialect]

	items := []RecognizedComplex{}
	for _, complex := range module.Complexes {
		if slices.Contains(want, complex.Compiler) {
			items = append(items, RecognizedComplex{
				Symbol:         complex.Name,
				ImportLocation: complex.Location,
			})
		}
	}
	return items
}

type CppModuleGenerationFlags struct {
	Actions *string
	Remotes *string
	Dtos    *string
}

func (x CppModuleGenerationFlags) filterList(raw *string) []string {
	if raw == nil || *raw == "" {
		return nil
	}
	return strings.Split(*raw, ",")
}

func readCppModuleFlags(ctx core.MicroGenContext) CppModuleGenerationFlags {
	config := CppModuleGenerationFlags{}
	if v, ok := ctx.Flags["actions"]; ok && v != "" {
		config.Actions = &v
	}
	if v, ok := ctx.Flags["remotes"]; ok && v != "" {
		config.Remotes = &v
	}
	if v, ok := ctx.Flags["dtos"]; ok && v != "" {
		config.Dtos = &v
	}
	return config
}

// CppModuleFullVirtualFiles compiles an entire Emi module into a C++ SDK - one
// header per dto/enum/action/remote, plus the embedded runtime (dialect-
// dependent) and a README, mirroring the equivalent full-module compilers in the
// sibling generators. No server/CLI/entity-persistence code is ever generated
// here - see the lib/cpp package doc comment.
func CppModuleFullVirtualFiles(module *core.Emi, ctx core.MicroGenContext) ([]core.VirtualFile, error) {
	dialect := ResolveDialect(ctx)
	complexes := DiscoverComplexes(module, dialect)
	config := readCppModuleFlags(ctx)
	files := []core.VirtualFile{}

	dtoFilter := config.filterList(config.Dtos)
	actionFilter := config.filterList(config.Actions)
	remoteFilter := config.filterList(config.Remotes)

	asDoc := func(chunk *core.CodeChunkCompiled) string {
		if dialect == DialectUnreal {
			return CppUnrealAsFullDocument(chunk, chunk.SuggestedFileName)
		}
		return CppGenericAsFullDocument(chunk)
	}

	for _, dto := range module.Dto {
		if len(dtoFilter) > 0 && !slices.Contains(dtoFilter, dto.Name) {
			continue
		}
		chunk, err := CppCommonObjectGenerator(dto.Fields, ctx, CppCommonObjectContext{
			Dialect:             dialect,
			RootClassName:       dto.GetClassName(),
			RecognizedComplexes: complexes,
		})
		if err != nil {
			return nil, err
		}
		files = append(files, core.VirtualFile{
			Name:         chunk.SuggestedFileName,
			Extension:    chunk.SuggestedExtension,
			ActualScript: asDoc(chunk),
		})
	}

	for _, enum := range module.Enums {
		chunk, err := CppStandaloneEnum(enum, dialect, ctx)
		if err != nil {
			return nil, err
		}
		files = append(files, core.VirtualFile{
			Name:         chunk.SuggestedFileName,
			Extension:    chunk.SuggestedExtension,
			ActualScript: asDoc(chunk),
		})
	}

	for _, action := range module.Actions {
		if len(actionFilter) > 0 && !slices.Contains(actionFilter, action.Name) {
			continue
		}
		chunk, err := CppActionRender(action, dialect, ctx, complexes)
		if err != nil {
			return nil, err
		}
		if chunk == nil {
			continue
		}
		files = append(files, core.VirtualFile{
			Name:         chunk.SuggestedFileName,
			Extension:    chunk.SuggestedExtension,
			ActualScript: asDoc(chunk),
		})
	}

	for _, remote := range module.Remotes {
		if len(remoteFilter) > 0 && !slices.Contains(remoteFilter, remote.Name) {
			continue
		}
		chunk, err := CppActionRender(remote, dialect, ctx, complexes)
		if err != nil {
			return nil, err
		}
		if chunk == nil {
			continue
		}
		files = append(files, core.VirtualFile{
			Name:         chunk.SuggestedFileName,
			Extension:    chunk.SuggestedExtension,
			ActualScript: asDoc(chunk),
		})
	}

	skipSdk := ctx.HasTag(NoSdk)
	if !skipSdk {
		if dialect == DialectUnreal {
			files = append(files, core.FsEmbedToVirtualFile(&cppIncludeUnreal.Content, "")...)
		} else {
			files = append(files, core.FsEmbedToVirtualFile(&cppIncludeGeneric.Content, "")...)
		}
	}

	skipPackage := ctx.HasTag(NoPackage)
	if !skipPackage {
		readme := cppGenericReadme
		if dialect == DialectUnreal {
			readme = cppUnrealReadme
		}
		files = append(files, core.VirtualFile{
			Name:         "README",
			Extension:    ".md",
			ActualScript: readme,
		})
	}

	return files, nil
}

const cppGenericReadme = `# Generated Emi C++ SDK (generic dialect)

Generated by the Emi compiler - do not edit by hand.

Portable ISO C++17: desktop/POSIX, ESP-IDF, and the Arduino framework all build
the same generated dto/action/enum headers unmodified. Every dto is a plain
value-semantics class (default-constructible, copyable, movable) with:

- ` + "`cJSON* ToJson() const`" + ` / ` + "`static T FromJson(const cJSON* json)`" + ` - the
  caller owns the returned cJSON tree from ` + "`ToJson()`" + ` and must ` + "`cJSON_Delete`" + ` it.
- ` + "`static T Parse(const std::string&)`" + ` / ` + "`std::string Dump() const`" + ` for the
  common "just give me a string" case.

Every generated action/remote function takes an ` + "`emi::EmiClientConfig&`" + ` (or uses
` + "`emi::EmiClientConfig::Default()`" + `) with a ` + "`transport`" + ` pointer you set once -
pick the ` + "`IEmiHttpTransport`" + ` implementation matching your platform:

| Platform          | Header                          | Notes                                  |
| ------------------ | -------------------------------- | ---------------------------------------- |
| Desktop/POSIX       | EmiHttpTransportCurl.hpp          | link ` + "`-lcurl`" + `                              |
| ESP-IDF              | EmiHttpTransportEspIdf.hpp        | add ` + "`esp_http_client`" + ` to component REQUIRES |
| Arduino (ESP32/ESP8266) | EmiHttpTransportArduino.hpp    | needs the "HTTPClient" Arduino library    |

` + "`method: reactive`" + ` actions use ` + "`emi::EmiWebSocketX`" + ` (EmiWebSocketX.hpp), a
minimal RFC 6455 client over ` + "`emi::IEmiByteStream`" + ` - EmiByteStreamPosix.hpp
(desktop + ESP-IDF) or EmiByteStreamArduino.hpp back it. See the doc comment on
EmiWebSocketX for its documented scope boundary (no fragmentation/permessage-deflate).

Build against the vendored cJSON (compile ` + "`cjson/cJSON.c`" + ` once into your program) -
same library the C target uses.
`

const cppUnrealReadme = `# Generated Emi C++ SDK (Unreal Engine dialect)

Generated by the Emi compiler - do not edit by hand.

Every dto is a ` + "`USTRUCT(BlueprintType)`" + ` with ` + "`UPROPERTY`" + ` fields - inspectable in
the editor and usable from Blueprint with no extra glue. (De)serialization goes
through Unreal's own reflection (` + "`FJsonObjectConverter::UStructToJsonObjectString`" + `
/ ` + "`FJsonObjectConverter::JsonObjectStringToUStruct<T>()`" + `, from the JsonUtilities
module) rather than any hand-generated code.

Add to your module's ` + "`Build.cs`" + `:

` + "```" + `csharp
PublicDependencyModuleNames.AddRange(new[] { "Json", "JsonUtilities", "HTTP", "WebSockets" });
` + "```" + `

- ` + "`EmiHttpClient.h`" + ` wraps ` + "`FHttpModule`" + ` for every generated action/remote call.
- ` + "`EmiWebSocketX.h`" + ` wraps Unreal's own ` + "`IWebSocket`" + ` (WebSockets module) for every
  ` + "`method: reactive`" + ` action, typed against the same generated USTRUCT dtos.

A field whose shape can't be reflected (a self-referencing struct, or an
unresolved/` + "`any`" + ` shape) is still a plain C++ member - just not a ` + "`UPROPERTY`" + ` (see
the comment above that field) - fully usable from C++, not from Blueprint/JSON.
`
