package org.example.inventory

import kotlinx.serialization.decodeFromString
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * ProductDtoFormState is generated by --tags android-forms (see the Makefile's
 * gen-inventory target and lib/kotlin/kotlin-form-state.go) - a Compose-friendly
 * holder (mutableStateOf fields, per-field validation errors, toDto()/fromDto()) a
 * caller building an Android form can bind directly to Compose TextFields and hand
 * straight to ProductCreateActionClient.compute(body = ...).
 */
class ProductFormStateTest {

    @Test
    fun `mutating state and calling toDto produces the expected dto`() {
        val state = ProductDtoFormState()

        state.title.value = "Widget"
        state.active.value = "true"
        state.viewCount.value = "10"
        state.smallCount.value = "12"
        state.bigCount.value = "14"
        state.ratio32.value = "1.5"
        state.ratio64.value = "2.5"
        state.status.value = "active"
        state.tags.value = """["a","b"]"""
        state.labelsMeta.value = """{"color":"red"}"""
        state.gallery.value = """[{"url":"https://example.com/1.png"}]"""
        state.specs.weightGrams.value = "500"
        state.price.value = """{"currency":"USD","minorUnits":1999}"""
        state.misc.value = "anything"
        state.featured.value = "true"
        state.viewCountOpt.value = "11"
        state.smallCountOpt.value = "13"
        state.bigCountOpt.value = "15"
        state.ratio32Opt.value = "1.75"
        state.ratio64Opt.value = "2.75"
        state.tagsOpt.value = """["c","d"]"""
        state.galleryOpt.value = """[{"url":"https://example.com/2.png"}]"""

        val dto = state.toDto()

        assertEquals("Widget", dto.title)
        assertEquals(true, dto.active)
        assertEquals(10, dto.viewCount)
        assertEquals(12, dto.smallCount)
        assertEquals(14L, dto.bigCount)
        assertEquals(1.5f, dto.ratio32)
        assertEquals(2.5, dto.ratio64)
        assertEquals("active", dto.status)
        assertEquals(listOf("a", "b"), dto.tags)
        assertEquals(mapOf("color" to "red"), dto.labelsMeta)
        assertEquals("https://example.com/1.png", dto.gallery[0].url)
        assertEquals(500, dto.specs.weightGrams)
        assertEquals(1999L, dto.price.minorUnits)
        assertEquals("anything", dto.misc)
    }

    // Every nullable field left at its initial empty-string state converts to
    // MaybeField(Maybe.Absent) - a fresh, untouched form describes "nothing entered"
    // for every optional field, exactly like a freshly-constructed dto would.
    @Test
    fun `untouched optional fields convert to absent`() {
        val state = ProductDtoFormState()
        state.active.value = "false"
        state.viewCount.value = "0"
        state.smallCount.value = "0"
        state.bigCount.value = "0"
        state.ratio32.value = "0"
        state.ratio64.value = "0"
        state.tags.value = "[]"
        state.labelsMeta.value = "{}"
        state.gallery.value = "[]"
        state.price.value = """{"currency":"USD","minorUnits":0}"""
        state.misc.value = ""

        val dto = state.toDto()

        assertEquals(emikot.Maybe.Absent, dto.sku.value)
        assertEquals(emikot.Maybe.Absent, dto.statusOpt.value)
        assertEquals(emikot.Maybe.Absent, dto.featured.value)
        assertEquals(emikot.Maybe.Absent, dto.category.value)
        assertEquals(emikot.Maybe.Absent, dto.invoiceLines.value)
    }

    // fromDto() seeds the state back from an existing dto - the realistic
    // "load a form from a server response" path, which always goes through JSON
    // decode first (see the class doc on emikot.toDisplayString).
    @Test
    fun `fromDto seeds state from a JSON-decoded dto`() {
        val json = Json { encodeDefaults = true }
        val original = sampleProduct()
        val decoded = json.decodeFromString<ProductDto>(json.encodeToString(original))

        val state = ProductDtoFormState()
        state.fromDto(decoded)

        assertEquals("Widget", state.title.value)
        assertEquals("true", state.active.value)
        assertEquals("500", state.specs.weightGrams.value)
        assertTrue(state.sku.value.isNotEmpty())
    }

    // A nested object field (specs) gets its own nested ProductDtoFormStateSpecs
    // sub-holder, not a JSON-text MutableState<String>.
    @Test
    fun `nested object field has its own sub-holder`() {
        val state = ProductDtoFormState()
        state.specs.weightGrams.value = "42"

        assertEquals(42, state.specs.toDto().weightGrams)
    }

    @Test
    fun `setError and clearing it round trips`() {
        val state = ProductDtoFormState()
        state.setError("title", "Title is required")
        assertEquals("Title is required", state.errors.value["title"])

        state.setError("title", null)
        assertNull(state.errors.value["title"])
    }
}
