package external

import (
	"fmt"
	"path/filepath"
	"testing"

	"github.com/torabian/emi/emigo"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

// These cover the exact same MOne (one/one?), MCollection (collection/collection?) and
// MArray (array/array?, including array nested inside object/object? containers)
// scenarios as actions_postgres_test.go, but against a throwaway sqlite file instead of
// a real Postgres instance - no docker-compose, no external service, just `go test`.
//
// This only became possible once uniqueId stopped depending on Postgres's own
// gen_random_uuid() column default (see go-entity-default-fields.go / the BeforeCreate
// hook in go-entity-render.go): sqlite has no dialect equivalent for that function, so
// before that fix AutoMigrate on sqlite either errored outright or silently produced
// empty uniqueIds. The BeforeCreate hook assigns the UUID in Go instead, which works
// identically on every gorm dialect - sqlite included.
//
// entity.emi.yml's own comments walk through each field's yaml declaration; this file's
// comments instead point at the generated Go shape each relation type produces, since
// that's what the payloads below are built against. See ../../../README or
// entity_sqlite_results.md (generated by this file, see the last test below) for the
// human-readable "yaml in, payload in" pairing the task asked for.

// openSqliteTestDB opens a fresh, empty sqlite database file inside t.TempDir() (removed
// automatically once the test finishes) and auto-migrates every table these tests touch.
// Mirrors openPostgresTestDB in actions_postgres_test.go, minus the docker dependency.
func openSqliteTestDB(t *testing.T) *gorm.DB {
	t.Helper()

	dbPath := filepath.Join(t.TempDir(), "entity.sqlite")
	db, err := gorm.Open(sqlite.Open(dbPath), &gorm.Config{Logger: logger.Default.LogMode(logger.Warn)})
	if err != nil {
		t.Fatalf("failed to open sqlite db at %s: %v", dbPath, err)
	}

	// gorm's AutoMigrate does not auto-discover has-many child row types through an
	// association field (Entity1Entity.Items) - each has to be listed explicitly, or
	// their tables never get created. This includes relations nested inside
	// object/object? containers (NestedContainer.NestedInner.NestedItems and friends).
	if err := db.AutoMigrate(
		&Entity2Entity{},
		&Entity1Entity{},
		&Entity1EntityItems{},
		&Entity1EntityItems2{},
		&Entity1EntityItemsSubItems{},
		&Entity1EntityItemsSubItemsSubSubItems{},
		&Entity1EntityNestedContainerNestedInnerNestedItems{},
		&Entity1EntityNestedContainerOptNestedInnerNestedItemsOpt{},
	); err != nil {
		t.Fatalf("AutoMigrate error: %v", err)
	}

	return db
}

// TestSqlite_AutoMigrateProducesExpectedSchema is the sqlite counterpart of
// runAutoMigrateAssertions (migrate_shared_test.go) - it needs a real Postgres/MySQL
// instance behind the `integration` build tag, this doesn't need anything at all.
func TestSqlite_AutoMigrateProducesExpectedSchema(t *testing.T) {
	db := openSqliteTestDB(t)
	m := db.Migrator()

	t.Run("one/one? produced real FK columns, not the DTO wrapper", func(t *testing.T) {
		if !m.HasColumn(&Entity1Entity{}, "OwnerId") {
			t.Error("expected OwnerId FK column on entity1_table")
		}
		if !m.HasColumn(&Entity1Entity{}, "ManagerId") {
			t.Error("expected ManagerId FK column on entity1_table")
		}
		if m.HasColumn(&Entity1Entity{}, "Owner") {
			t.Error("did not expect a column for the Owner DTO field itself (gorm:\"-\")")
		}
	})

	t.Run("array/array? produced real has-many child tables with LinkerId", func(t *testing.T) {
		if !m.HasTable(&Entity1EntityItems{}) {
			t.Error("expected a table for Entity1EntityItems (has-many child rows)")
		}
		if !m.HasColumn(&Entity1EntityItems{}, "LinkerId") {
			t.Error("expected LinkerId FK column on the Entity1EntityItems child table")
		}
		if !m.HasTable(&Entity1EntityItems2{}) {
			t.Error("expected a table for Entity1EntityItems2 (has-many child rows)")
		}
	})

	t.Run("collection/collection? produced a many2many join table", func(t *testing.T) {
		if !m.HasTable("entity1_items3") {
			t.Error("expected join table entity1_items3 for the Items3 many2many relation")
		}
		if !m.HasTable("entity1_items4") {
			t.Error("expected join table entity1_items4 for the Items4 many2many relation")
		}
	})

	t.Run("array nested 2 objects deep still produced its own child table", func(t *testing.T) {
		if !m.HasTable(&Entity1EntityNestedContainerNestedInnerNestedItems{}) {
			t.Error("expected a table for the nested has-many child rows (NestedContainer.NestedInner.NestedItems)")
		}
	})
}

// TestSqlite_OneField_CreateResolvesOwnerAndPersistsForeignKey covers a plain "one"
// (MOne, required) field end to end via Entity1EntityActions.Create: entity1.owner ->
// Entity2Entity, wired through the generated OwnerId column.
func TestSqlite_OneField_CreateResolvesOwnerAndPersistsForeignKey(t *testing.T) {
	db := openSqliteTestDB(t)

	owner := &Entity2Entity{UniqueId: "owner-1", Label2: "owner-one"}
	if err := db.Create(owner).Error; err != nil {
		t.Fatalf("seed owner error: %v", err)
	}

	dto := &Entity1Entity{Title: "hello", IsActive: true, Owner: owner}
	created, err := Entity1EntityActions.Create(db, dto)
	if err != nil {
		t.Fatalf("Create error: %v", err)
	}
	if created.UniqueId == "" {
		t.Fatal("expected BeforeCreate to assign a UniqueId (no gen_random_uuid() on sqlite)")
	}

	var reloaded Entity1Entity
	if err := db.Preload("Owner").First(&reloaded, "unique_id = ?", created.UniqueId).Error; err != nil {
		t.Fatalf("reload error: %v", err)
	}
	if reloaded.Owner == nil || reloaded.Owner.Label2 != "owner-one" {
		t.Fatalf("expected owner to resolve to owner-one, got %+v", reloaded.Owner)
	}
	if reloaded.OwnerId != owner.Id {
		t.Fatalf("expected OwnerId = owner.Id (%d), got %d", owner.Id, reloaded.OwnerId)
	}
}

// TestSqlite_OneField_UpdateChangesOwnerViaSelect covers MOne's Update-time "select an
// existing row by uniqueId" shape (input.Owner.SetSelector), mirrored from
// TestEntity1EntityUpdateFn_OneChangesOwnerViaSelect in actions_postgres_test.go.
func TestSqlite_OneField_UpdateChangesOwnerViaSelect(t *testing.T) {
	db := openSqliteTestDB(t)

	owner1 := Entity2Entity{UniqueId: "owner-1", Label2: "owner-one"}
	owner2 := Entity2Entity{UniqueId: "owner-2", Label2: "owner-two"}
	if err := db.Create(&owner1).Error; err != nil {
		t.Fatalf("seed owner1 error: %v", err)
	}
	if err := db.Create(&owner2).Error; err != nil {
		t.Fatalf("seed owner2 error: %v", err)
	}

	dto := &Entity1Entity{Title: "hello", Owner: &owner1}
	created, err := Entity1EntityActions.Create(db, dto)
	if err != nil {
		t.Fatalf("Create error: %v", err)
	}

	var input Entity1OptionalDto
	input.Owner.SetSelector("owner-2")
	updated, err := Entity1EntityActions.Update(db, created.UniqueId, input)
	if err != nil {
		t.Fatalf("Update error: %v", err)
	}
	if updated.OwnerId != owner2.Id {
		t.Fatalf("expected OwnerId = owner2.Id (%d), got %d", owner2.Id, updated.OwnerId)
	}
}

// TestSqlite_CollectionField_CreateAndAppend covers MCollection (many-to-many) end to
// end: Create wires the initial join rows, and Update's "append" operation adds more
// without disturbing the pre-existing targets.
func TestSqlite_CollectionField_CreateAndAppend(t *testing.T) {
	db := openSqliteTestDB(t)

	tagA := Entity2Entity{UniqueId: "tag-a", Label2: "tag-a"}
	tagB := Entity2Entity{UniqueId: "tag-b", Label2: "tag-b"}
	if err := db.Create(&tagA).Error; err != nil {
		t.Fatalf("seed tagA error: %v", err)
	}
	if err := db.Create(&tagB).Error; err != nil {
		t.Fatalf("seed tagB error: %v", err)
	}

	dto := &Entity1Entity{Title: "hello", Items3: emigo.CollectionReplace([]Entity2Entity{tagA})}
	created, err := Entity1EntityActions.Create(db, dto)
	if err != nil {
		t.Fatalf("Create error: %v", err)
	}

	var reloaded Entity1Entity
	if err := db.Preload("Items3Row").First(&reloaded, "unique_id = ?", created.UniqueId).Error; err != nil {
		t.Fatalf("reload error: %v", err)
	}
	if len(reloaded.Items3Row) != 1 {
		t.Fatalf("expected 1 collection target right after create, got %d", len(reloaded.Items3Row))
	}

	// Entity1OptionalDto.Items3 targets Entity2Dto (the portable dto), not
	// Entity2Entity, so tagB is referenced by UniqueId alone.
	var input Entity1OptionalDto
	input.Items3.Set("append", []Entity2Dto{{UniqueId: emigo.NullableOf(tagB.UniqueId)}})
	if _, err := Entity1EntityActions.Update(db, created.UniqueId, input); err != nil {
		t.Fatalf("Update error: %v", err)
	}

	if err := db.Preload("Items3Row").First(&reloaded, "unique_id = ?", created.UniqueId).Error; err != nil {
		t.Fatalf("reload (after append) error: %v", err)
	}
	if len(reloaded.Items3Row) != 2 {
		t.Fatalf("expected 2 tags after append, got %d", len(reloaded.Items3Row))
	}

	// append/replace on a many2many must never delete the target entity itself.
	var tagACheck Entity2Entity
	if err := db.First(&tagACheck, "unique_id = ?", "tag-a").Error; err != nil {
		t.Fatalf("expected tag-a to still exist: %v", err)
	}
}

// TestSqlite_ArrayField_CreateAndReplace covers a plain top-level MArray (has-many
// child struct) end to end: Create inserts the children, and Update's "replace"
// operation reconciles them (drop/modify/add) against the existing rows, deleting
// orphans outright rather than merely unlinking them.
func TestSqlite_ArrayField_CreateAndReplace(t *testing.T) {
	db := openSqliteTestDB(t)

	dto := &Entity1Entity{
		Title: "hello",
		Items: []*Entity1EntityItems{
			{UniqueId: "c1", Item2: "child-1"},
			{UniqueId: "c2", Item2: "child-2"},
		},
	}
	created, err := Entity1EntityActions.Create(db, dto)
	if err != nil {
		t.Fatalf("Create error: %v", err)
	}

	var input Entity1OptionalDto
	input.Items.Set("replace", []Entity1OptionalDtoItems{
		{UniqueId: emigo.NullableOf("c2"), Item2: "child-2-updated"},
		{UniqueId: emigo.NullableOf("c3"), Item2: "child-3"},
	})
	if _, err := Entity1EntityActions.Update(db, created.UniqueId, input); err != nil {
		t.Fatalf("Update error: %v", err)
	}

	var children []Entity1EntityItems
	if err := db.Where("linker_id = ?", created.Id).Order("unique_id").Find(&children).Error; err != nil {
		t.Fatalf("query children error: %v", err)
	}
	if len(children) != 2 {
		t.Fatalf("expected 2 children after replace, got %d: %+v", len(children), children)
	}
	if children[0].UniqueId != "c2" || children[0].Item2 != "child-2-updated" {
		t.Fatalf("expected c2 to be updated in place, got %+v", children[0])
	}
	if children[1].UniqueId != "c3" || children[1].Item2 != "child-3" {
		t.Fatalf("expected c3 to be newly created, got %+v", children[1])
	}

	// c1 must be actually gone, not just orphaned.
	var c1Check []Entity1EntityItems
	db.Unscoped().Where("unique_id = ?", "c1").Find(&c1Check)
	if len(c1Check) != 0 {
		t.Fatalf("expected c1 to be deleted, found %d rows", len(c1Check))
	}
}

// TestSqlite_NestedArray_CreateAndReplace covers MArray nested 2 objects deep
// (nestedContainer.nestedInner.nestedItems) - the scenario nested_relations_test.go
// verifies structurally (gorm tags/schema.Parse) without a live database. This is the
// same relation exercised end-to-end against a real database.
func TestSqlite_NestedArray_CreateAndReplace(t *testing.T) {
	db := openSqliteTestDB(t)

	owner := Entity2Entity{UniqueId: "nested-owner-1", Label2: "nested-owner"}
	if err := db.Create(&owner).Error; err != nil {
		t.Fatalf("seed owner error: %v", err)
	}

	dto := &Entity1Entity{
		Title: "hello",
		NestedContainer: Entity1EntityNestedContainer{
			NestedInner: Entity1EntityNestedContainerNestedInner{
				NestedItems: []*Entity1EntityNestedContainerNestedInnerNestedItems{
					{Label: "nested-child-1"},
					{Label: "nested-child-2"},
				},
				NestedOwner: &owner,
			},
		},
	}
	created, err := Entity1EntityActions.Create(db, dto)
	if err != nil {
		t.Fatalf("Create error: %v", err)
	}

	var reloaded Entity1Entity
	if err := db.Preload("NestedContainer.NestedInner.NestedItems").
		Preload("NestedContainer.NestedInner.NestedOwner").
		First(&reloaded, "unique_id = ?", created.UniqueId).Error; err != nil {
		t.Fatalf("reload error: %v", err)
	}

	nested := reloaded.NestedContainer.NestedInner
	if len(nested.NestedItems) != 2 {
		t.Fatalf("expected 2 nested array children, got %d", len(nested.NestedItems))
	}
	if nested.NestedOwner == nil || nested.NestedOwner.Label2 != "nested-owner" {
		t.Fatalf("expected nested owner to resolve to nested-owner, got %+v", nested.NestedOwner)
	}

	// Update: replace the nested array (drop one, modify one, add one) through two
	// levels of object containers - the same reconcile guarantees as a top-level
	// array, just reached via NestedContainer -> NestedInner -> NestedItems.
	var input Entity1OptionalDto
	input.NestedContainer.Set(&Entity1OptionalDtoNestedContainer{})
	nc, _ := input.NestedContainer.Get()
	nc.NestedInner.Set(&Entity1OptionalDtoNestedContainerNestedInner{})
	ni, _ := nc.NestedInner.Get()
	ni.NestedItems.Set("replace", []Entity1OptionalDtoNestedContainerNestedInnerNestedItems{
		{UniqueId: emigo.NullableOf(nested.NestedItems[1].UniqueId), Label: "nested-child-2-updated"},
		{Label: "nested-child-3"},
	})
	if _, err := Entity1EntityActions.Update(db, created.UniqueId, input); err != nil {
		t.Fatalf("Update error: %v", err)
	}

	var afterUpdate Entity1Entity
	if err := db.Preload("NestedContainer.NestedInner.NestedItems").
		First(&afterUpdate, "unique_id = ?", created.UniqueId).Error; err != nil {
		t.Fatalf("reload error: %v", err)
	}
	items := afterUpdate.NestedContainer.NestedInner.NestedItems
	if len(items) != 2 {
		t.Fatalf("expected 2 nested children after replace, got %d", len(items))
	}
	byLabel := map[string]bool{}
	for _, it := range items {
		byLabel[it.Label] = true
	}
	if !byLabel["nested-child-2-updated"] || !byLabel["nested-child-3"] {
		t.Fatalf("unexpected nested children after replace: %+v", items)
	}
}

// TestSqlite_EverythingTogether_CreateOneRowWithAllThreeRelationTypes covers array,
// collection, and one all cascading from a single Entity1EntityActions.Create call -
// the sqlite counterpart of TestEntity1EntityCreateFn_CascadesArrayCollectionOne in
// actions_postgres_test.go.
func TestSqlite_EverythingTogether_CreateOneRowWithAllThreeRelationTypes(t *testing.T) {
	db := openSqliteTestDB(t)

	owner := &Entity2Entity{UniqueId: "owner-1", Label2: "owner-one"}
	tagA := &Entity2Entity{UniqueId: "tag-a", Label2: "tag-a"}
	tagB := &Entity2Entity{UniqueId: "tag-b", Label2: "tag-b"}
	if err := db.Create(owner).Error; err != nil {
		t.Fatalf("seed owner error: %v", err)
	}
	if err := db.Create(tagA).Error; err != nil {
		t.Fatalf("seed tagA error: %v", err)
	}
	if err := db.Create(tagB).Error; err != nil {
		t.Fatalf("seed tagB error: %v", err)
	}

	dto := &Entity1Entity{
		Title:    "hello",
		IsActive: true,
		Items: []*Entity1EntityItems{
			{Item2: "child-1"},
			{Item2: "child-2"},
		},
		Items3: emigo.CollectionReplace([]Entity2Entity{*tagA, *tagB}),
		Owner:  owner,
	}

	created, err := Entity1EntityActions.Create(db, dto)
	if err != nil {
		t.Fatalf("Create error: %v", err)
	}
	if created.UniqueId == "" {
		t.Fatal("expected BeforeCreate to assign a UniqueId")
	}
	if created.Id == 0 {
		t.Fatal("expected sqlite to assign an Id via autoIncrement")
	}

	var reloaded Entity1Entity
	if err := db.Preload("Items").Preload("Items3Row").Preload("Owner").
		First(&reloaded, "unique_id = ?", created.UniqueId).Error; err != nil {
		t.Fatalf("reload error: %v", err)
	}

	if len(reloaded.Items) != 2 {
		t.Fatalf("expected 2 array children, got %d", len(reloaded.Items))
	}
	if len(reloaded.Items3Row) != 2 {
		t.Fatalf("expected 2 collection targets, got %d", len(reloaded.Items3Row))
	}
	if reloaded.Owner == nil || reloaded.Owner.Label2 != "owner-one" {
		t.Fatalf("expected owner to resolve to owner-one, got %+v", reloaded.Owner)
	}
	if reloaded.OwnerId != owner.Id {
		t.Fatalf("expected OwnerId = owner.Id (%d), got %d", owner.Id, reloaded.OwnerId)
	}
}

// TestSqlite_ArrayInsideArray_DeleteRemovesOnlySelectedItems covers the "delete"
// operation (see emigorm.ReconcileHasMany) on an array nested inside another array -
// items[].subItems[].subSubItems[], 3 levels deep (entity.emi.yml's own "items" field).
// It creates a single top-level item with 5 subItems, two of them (sub-2 and sub-3)
// carrying their own subSubItems, then updates with a "delete" selector naming sub-2
// and sub-4 by uniqueId - the same delete works at any nesting depth, not just the top
// level: buildArrayItemFields (lib/golang/go-entity-actions.go) recurses into an
// array's own nested array fields, generating the identical reconcile call one level
// down, however deep the schema goes. sub-2 being deleted while carrying its own
// subSubItems also proves the delete doesn't leave grandchild orphans behind:
// emigorm.ReconcileHasMany's "delete" branch reuses the same
// Select(clause.Associations).Delete(&existing) gorm already uses for "replace"'s own
// orphan cleanup, which cascades through has-many children exactly the same way.
func TestSqlite_ArrayInsideArray_DeleteRemovesOnlySelectedItems(t *testing.T) {
	db := openSqliteTestDB(t)

	subItems := make([]Entity1OptionalDtoItemsSubItems, 5)
	for i := range subItems {
		subItems[i] = Entity1OptionalDtoItemsSubItems{
			SubLabel: fmt.Sprintf("sub-%d", i+1),
		}
	}
	// sub-2 (index 1, about to be deleted) and sub-3 (index 2, kept) both carry their
	// own subSubItems - proves level-3 (the deepest array in this schema) is created
	// correctly via plain gorm cascade on Create, and lets the delete assertions below
	// distinguish "cascaded away with its deleted parent" from "survived untouched".
	subItems[1].SubSubItems = emigo.ArrayNullableReplace([]Entity1OptionalDtoItemsSubItemsSubSubItems{
		{LeafLabel: "leaf-deleted-with-sub-2"},
	})
	subItems[2].SubSubItems = emigo.ArrayNullableReplace([]Entity1OptionalDtoItemsSubItemsSubSubItems{
		{LeafLabel: "leaf-kept-on-sub-3"},
	})

	dto := &Entity1Entity{
		Title: "hello",
		Items: []*Entity1EntityItems{
			{Item2: "parent-item"},
		},
	}
	created, err := Entity1EntityActions.Create(db, dto)
	if err != nil {
		t.Fatalf("Create error: %v", err)
	}

	// entity1's own Create path (Entity1EntityCreateFn) takes the entity struct
	// directly and relies on gorm's automatic cascade for array children (see
	// walkCreateFields's own comment) - which does not run the Operation-wrapped
	// dto conversion buildArrayItemFields generates for Update. So the 5 subItems
	// (level 2, needed to exercise "delete" against) are seeded via a real Update
	// "replace" first, exactly the way a caller would populate them through the API.
	var seed Entity1OptionalDto
	seed.Items.Set("replace", []Entity1OptionalDtoItems{
		{UniqueId: emigo.NullableOf(created.Items[0].UniqueId), Item2: "parent-item", SubItems: emigo.ArrayNullableReplace(subItems)},
	})
	if _, err := Entity1EntityActions.Update(db, created.UniqueId, seed); err != nil {
		t.Fatalf("seed Update error: %v", err)
	}

	var afterSeed Entity1Entity
	if err := db.Preload("Items.SubItems.SubSubItems").
		First(&afterSeed, "unique_id = ?", created.UniqueId).Error; err != nil {
		t.Fatalf("reload after seed error: %v", err)
	}
	if len(afterSeed.Items) != 1 || len(afterSeed.Items[0].SubItems) != 5 {
		t.Fatalf("expected 1 item with 5 subItems after seeding, got %+v", afterSeed.Items)
	}
	leaf := afterSeed.Items[0]
	var toDelete []string
	for _, si := range leaf.SubItems {
		if si.SubLabel == "sub-2" || si.SubLabel == "sub-4" {
			toDelete = append(toDelete, si.UniqueId)
		}
	}
	if len(toDelete) != 2 {
		t.Fatalf("expected to find sub-2 and sub-4 among the seeded subItems, got %+v", leaf.SubItems)
	}
	// sub-2 and sub-3's own subSubItems must have made it through the cascade create.
	var sub2Leaf, sub3Leaf string
	for _, si := range leaf.SubItems {
		switch si.SubLabel {
		case "sub-2":
			if len(si.SubSubItems) == 1 {
				sub2Leaf = si.SubSubItems[0].LeafLabel
			}
		case "sub-3":
			if len(si.SubSubItems) == 1 {
				sub3Leaf = si.SubSubItems[0].LeafLabel
			}
		}
	}
	if sub2Leaf != "leaf-deleted-with-sub-2" || sub3Leaf != "leaf-kept-on-sub-3" {
		t.Fatalf("expected sub-2/sub-3 to each carry their own subSubItems leaf, got %+v", leaf.SubItems)
	}

	// The actual delete: a plain {"uniqueId": "..."} per row is all "delete" ever
	// reads (see emigo.Array's own doc comment / emigorm.ReconcileHasMany) - no
	// other field needs to be sent.
	deleteItems := make([]Entity1OptionalDtoItemsSubItems, len(toDelete))
	for i, uid := range toDelete {
		deleteItems[i] = Entity1OptionalDtoItemsSubItems{UniqueId: emigo.NullableOf(uid)}
	}

	var input Entity1OptionalDto
	input.Items.Set("replace", []Entity1OptionalDtoItems{
		{UniqueId: emigo.NullableOf(created.Items[0].UniqueId), Item2: "parent-item", SubItems: emigo.ArrayNullableDelete(deleteItems)},
	})
	if _, err := Entity1EntityActions.Update(db, created.UniqueId, input); err != nil {
		t.Fatalf("delete Update error: %v", err)
	}

	var afterDelete Entity1Entity
	if err := db.Preload("Items.SubItems.SubSubItems").
		First(&afterDelete, "unique_id = ?", created.UniqueId).Error; err != nil {
		t.Fatalf("reload after delete error: %v", err)
	}
	remaining := afterDelete.Items[0].SubItems
	if len(remaining) != 3 {
		t.Fatalf("expected 3 subItems to remain after deleting 2 of 5, got %d: %+v", len(remaining), remaining)
	}
	byLabel := map[string]bool{}
	for _, si := range remaining {
		byLabel[si.SubLabel] = true
	}
	if byLabel["sub-2"] || byLabel["sub-4"] {
		t.Fatalf("expected sub-2 and sub-4 to be gone, got %+v", remaining)
	}
	if !byLabel["sub-1"] || !byLabel["sub-3"] || !byLabel["sub-5"] {
		t.Fatalf("expected sub-1, sub-3 and sub-5 to still be present, got %+v", remaining)
	}

	// sub-2/sub-4 must be actually gone, not just orphaned.
	var deletedCheck []Entity1EntityItemsSubItems
	db.Unscoped().Where("unique_id IN ?", toDelete).Find(&deletedCheck)
	if len(deletedCheck) != 0 {
		t.Fatalf("expected sub-2/sub-4 rows to be hard-deleted, found %d", len(deletedCheck))
	}

	// sub-2's own subSubItems row (leaf-deleted-with-sub-2) must have cascaded away
	// with it - a level-3 orphan left behind would be exactly the bug this test
	// exists to catch.
	var orphanCheck []Entity1EntityItemsSubItemsSubSubItems
	db.Unscoped().Where("leaf_label = ?", "leaf-deleted-with-sub-2").Find(&orphanCheck)
	if len(orphanCheck) != 0 {
		t.Fatalf("expected sub-2's own subSubItems row to be gone along with it, found %d orphan(s)", len(orphanCheck))
	}

	// sub-3 (never touched by the delete) must still carry its own subSubItems leaf -
	// deleting sibling subItems must never disturb an untouched one's own children.
	for _, si := range remaining {
		if si.SubLabel == "sub-3" {
			if len(si.SubSubItems) != 1 || si.SubSubItems[0].LeafLabel != "leaf-kept-on-sub-3" {
				t.Fatalf("expected sub-3 to still carry leaf-kept-on-sub-3, got %+v", si.SubSubItems)
			}
		}
	}
}
