/*
 * EmiByteStreamPosix - plain blocking BSD sockets. Works unmodified under
 * ESP-IDF (lwIP implements the same socket API) as well as desktop/POSIX.
 *
 * No TLS support (`ws://`/plain TCP only) - for `wss://` on ESP-IDF, wrap esp-tls
 * (or mbedTLS directly) behind your own IEmiByteStream instead.
 *
 * Generated by the Emi compiler - do not edit by hand.
 */
#pragma once

#include "EmiByteStream.hpp"

#include <cstring>
#include <netdb.h>
#include <sys/socket.h>
#include <unistd.h>

namespace emi {

class EmiByteStreamPosix : public IEmiByteStream {
public:
    ~EmiByteStreamPosix() override { Close(); }

    bool Connect(const std::string& host, uint16_t port) override {
        struct addrinfo hints;
        std::memset(&hints, 0, sizeof(hints));
        hints.ai_family = AF_UNSPEC;
        hints.ai_socktype = SOCK_STREAM;

        struct addrinfo* result = nullptr;
        std::string portStr = std::to_string(port);
        if (getaddrinfo(host.c_str(), portStr.c_str(), &hints, &result) != 0) {
            return false;
        }

        for (struct addrinfo* rp = result; rp != nullptr; rp = rp->ai_next) {
            fd_ = socket(rp->ai_family, rp->ai_socktype, rp->ai_protocol);
            if (fd_ < 0) continue;
            if (connect(fd_, rp->ai_addr, rp->ai_addrlen) == 0) {
                freeaddrinfo(result);
                return true;
            }
            ::close(fd_);
            fd_ = -1;
        }
        freeaddrinfo(result);
        return false;
    }

    int Read(uint8_t* buffer, size_t length) override {
        if (fd_ < 0) return -1;
        return (int) recv(fd_, buffer, length, 0);
    }

    bool Write(const uint8_t* buffer, size_t length) override {
        if (fd_ < 0) return false;
        size_t sent = 0;
        while (sent < length) {
            ssize_t n = send(fd_, buffer + sent, length - sent, 0);
            if (n <= 0) return false;
            sent += (size_t) n;
        }
        return true;
    }

    bool IsConnected() override { return fd_ >= 0; }

    void Close() override {
        if (fd_ >= 0) {
            ::close(fd_);
            fd_ = -1;
        }
    }

private:
    int fd_ = -1;
};

} // namespace emi
