/*
 * IEmiByteStream - the transport seam EmiWebSocketX (see EmiWebSocketX.hpp) speaks
 * over: a plain, blocking, already-connected byte pipe. Two implementations are
 * shipped - EmiByteStreamPosix.hpp (desktop AND ESP-IDF, whose lwIP stack exposes
 * the same BSD sockets API) and EmiByteStreamArduino.hpp (any Arduino `Client`,
 * e.g. WiFiClient/WiFiClientSecure). Bring your own for anything else - a
 * platform's raw socket API only ever needs to fill in these five methods.
 *
 * Generated by the Emi compiler - do not edit by hand.
 */
#pragma once

#include <cstddef>
#include <cstdint>
#include <string>

namespace emi {

class IEmiByteStream {
public:
    virtual ~IEmiByteStream() = default;

    virtual bool Connect(const std::string& host, uint16_t port) = 0;

    // Returns the number of bytes actually read (0 on a clean close, negative on
    // a transport error) - never blocks forever on an EmiByteStreamPosix (it's a
    // plain blocking recv()), but EmiByteStreamArduino's Read() does poll until at
    // least one byte is available or the connection drops.
    virtual int Read(uint8_t* buffer, size_t length) = 0;

    // Returns true only once every byte has been written.
    virtual bool Write(const uint8_t* buffer, size_t length) = 0;

    virtual bool IsConnected() = 0;

    virtual void Close() = 0;
};

} // namespace emi
