/*
 * EmiByteStreamArduino - IEmiByteStream implementation over any Arduino `Client`
 * (WiFiClient for `ws://`, WiFiClientSecure for `wss://`).
 *
 * Same scope boundary as EmiHttpTransportArduino.hpp: needs a real C++17 STL, so
 * this targets 32-bit Arduino cores (ESP32/ESP8266 and similar) - not classic
 * 8-bit AVR boards.
 *
 * Generated by the Emi compiler - do not edit by hand.
 */
#pragma once

#ifndef ARDUINO
#error "EmiByteStreamArduino.hpp requires the Arduino framework (ARDUINO is not defined) - include EmiByteStreamPosix.hpp instead."
#endif

#include "EmiByteStream.hpp"

#include <Arduino.h>
#include <Client.h>

namespace emi {

class EmiByteStreamArduino : public IEmiByteStream {
public:
    explicit EmiByteStreamArduino(Client& client) : client_(client) {}

    bool Connect(const std::string& host, uint16_t port) override {
        return client_.connect(host.c_str(), port) != 0;
    }

    int Read(uint8_t* buffer, size_t length) override {
        if (!client_.connected()) return -1;
        while (client_.connected() && client_.available() == 0) {
            delay(1);
        }
        int available = client_.available();
        if (available <= 0) return client_.connected() ? 0 : -1;
        size_t want = length < (size_t) available ? length : (size_t) available;
        return client_.read(buffer, want);
    }

    bool Write(const uint8_t* buffer, size_t length) override {
        return client_.write(buffer, length) == length;
    }

    bool IsConnected() override { return client_.connected(); }

    void Close() override { client_.stop(); }

private:
    Client& client_;
};

} // namespace emi
