/*
 * EmiHttpTransportEspIdf - IEmiHttpTransport implementation for the bare ESP-IDF
 * SDK, on top of esp_http_client. Add `esp_http_client` to your component's
 * `REQUIRES`/`PRIV_REQUIRES` (idf.py component).
 *
 * Generated by the Emi compiler - do not edit by hand.
 */
#pragma once

#ifndef ESP_PLATFORM
#error "EmiHttpTransportEspIdf.hpp requires an ESP-IDF build (ESP_PLATFORM is not defined) - include EmiHttpTransportCurl.hpp or EmiHttpTransportArduino.hpp instead."
#endif

#include "EmiHttpTransport.hpp"

#include "esp_http_client.h"

namespace emi {

class EmiHttpTransportEspIdf : public IEmiHttpTransport {
public:
    EmiHttpResponse Send(const EmiHttpRequest& request) override {
        EmiHttpResponse response;
        std::string buffer;

        esp_http_client_config_t config = {};
        config.url = request.url.c_str();
        config.event_handler = &EmiHttpTransportEspIdf::EventHandler;
        config.user_data = &buffer;
        // esp_http_client keeps its own copy of `config.url` internally once
        // esp_http_client_init() returns, so `request`/`buffer` going out of scope
        // right after Send() returns is safe.

        esp_http_client_handle_t client = esp_http_client_init(&config);
        esp_http_client_set_method(client, MethodFromString(request.method));
        for (const auto& h : request.headers) {
            esp_http_client_set_header(client, h.name.c_str(), h.value.c_str());
        }
        if (!request.body.empty()) {
            esp_http_client_set_header(client, "Content-Type", "application/json");
            esp_http_client_set_post_field(client, request.body.c_str(), (int) request.body.size());
        }

        esp_err_t err = esp_http_client_perform(client);
        if (err == ESP_OK) {
            response.statusCode = esp_http_client_get_status_code(client);
            response.body = buffer;
            response.ok = response.statusCode < 400;
        } else {
            response.ok = false;
            response.error = esp_err_to_name(err);
        }

        esp_http_client_cleanup(client);
        return response;
    }

private:
    static esp_http_client_method_t MethodFromString(const std::string& method) {
        if (method == "GET") return HTTP_METHOD_GET;
        if (method == "POST") return HTTP_METHOD_POST;
        if (method == "PUT") return HTTP_METHOD_PUT;
        if (method == "DELETE") return HTTP_METHOD_DELETE;
        if (method == "PATCH") return HTTP_METHOD_PATCH;
        if (method == "HEAD") return HTTP_METHOD_HEAD;
        return HTTP_METHOD_GET;
    }

    static esp_err_t EventHandler(esp_http_client_event_t* evt) {
        if (evt->event_id == HTTP_EVENT_ON_DATA && evt->user_data) {
            auto* buffer = static_cast<std::string*>(evt->user_data);
            buffer->append((const char*) evt->data, evt->data_len);
        }
        return ESP_OK;
    }
};

} // namespace emi
