/*
 * EmiHttpTransport - the platform seam every generated action call (see
 * cpp-action-render.go) goes through. IEmiHttpTransport is the only thing
 * generated code depends on directly; exactly one concrete implementation needs
 * to exist per platform - EmiHttpTransportCurl.hpp (desktop/POSIX, the reference
 * implementation), EmiHttpTransportEspIdf.hpp (ESP-IDF's esp_http_client) and
 * EmiHttpTransportArduino.hpp (the Arduino HTTPClient library) are shipped here.
 * Swapping platforms is a constructor argument (EmiClientConfig::transport), not
 * a regenerate - bring your own IEmiHttpTransport for anything else.
 *
 * Generated by the Emi compiler - do not edit by hand.
 */
#pragma once

#include <cctype>
#include <cstdint>
#include <string>
#include <vector>

namespace emi {

struct EmiHttpHeader {
    std::string name;
    std::string value;
};

struct EmiHttpRequest {
    std::string method; // "GET", "POST", ...
    std::string url;    // fully resolved (base + path + query)
    std::string body;   // raw request body, empty if none
    std::vector<EmiHttpHeader> headers;
};

struct EmiHttpResponse {
    bool ok = false; // false on a transport-level failure - see `error`
    int32_t statusCode = 0;
    std::string body;
    std::string error; // only set when !ok
};

class IEmiHttpTransport {
public:
    virtual ~IEmiHttpTransport() = default;
    virtual EmiHttpResponse Send(const EmiHttpRequest& request) = 0;
};

// Carries the base url + default headers + transport for every generated action
// method. Build one per client instance, or rely on EmiClientConfig::Default()
// for a single process-wide instance (mirrors FetchxContext/DefaultContext in the
// sibling C/C# targets).
class EmiClientConfig {
public:
    std::string baseUrl;
    std::vector<EmiHttpHeader> defaultHeaders;
    IEmiHttpTransport* transport = nullptr; // not owned - set this before calling any generated action

    static EmiClientConfig& Default() {
        static EmiClientConfig instance;
        return instance;
    }
};

// ---- url helpers ------------------------------------------------------------

// Joins a base url with a (possibly already-parameterized) path, collapsing
// duplicate slashes at the seam.
inline std::string EmiBuildUrl(const std::string& baseUrl, const std::string& templateUrl) {
    if (baseUrl.empty()) return templateUrl;
    std::string base = baseUrl;
    while (!base.empty() && base.back() == '/') base.pop_back();
    size_t start = 0;
    while (start < templateUrl.size() && templateUrl[start] == '/') start++;
    return base + "/" + templateUrl.substr(start);
}

// Percent-encodes `value` for safe use as a query string key/value.
inline std::string EmiUrlEncode(const std::string& value) {
    static const char* hex = "0123456789ABCDEF";
    std::string out;
    out.reserve(value.size());
    for (unsigned char c : value) {
        if (std::isalnum(c) || c == '-' || c == '_' || c == '.' || c == '~') {
            out.push_back((char) c);
        } else {
            out.push_back('%');
            out.push_back(hex[c >> 4]);
            out.push_back(hex[c & 0x0F]);
        }
    }
    return out;
}

// Replaces the first occurrence of `placeholder` (e.g. ":id") with `replacement`.
inline std::string EmiUrlReplace(const std::string& url, const std::string& placeholder, const std::string& replacement) {
    size_t pos = url.find(placeholder);
    if (pos == std::string::npos) return url;
    std::string out = url;
    out.replace(pos, placeholder.size(), replacement);
    return out;
}

// Appends `key=value` to `url` (as the first `?param` or an additional `&param`),
// url-encoding both.
inline std::string EmiUrlAppendQuery(const std::string& url, const std::string& key, const std::string& value) {
    bool hasQuery = url.find('?') != std::string::npos;
    return url + (hasQuery ? "&" : "?") + EmiUrlEncode(key) + "=" + EmiUrlEncode(value);
}

} // namespace emi
