/*
 * EmiHttpTransportArduino - IEmiHttpTransport implementation for the Arduino
 * framework, on top of the "HTTPClient" library bundled with the ESP32/ESP8266
 * Arduino cores. Pass a plain WiFiClient for `http://` base urls, or a
 * WiFiClientSecure for `https://`.
 *
 * Scope boundary (documented, not an oversight): this whole generic C++ dialect
 * needs a real C++17 STL (std::optional/std::vector/std::map/std::function, used
 * throughout every generated dto/action - see cpp-include/generic's other
 * headers), which classic 8-bit AVR boards (Uno/Nano/Mega, avr-gcc) don't
 * provide and couldn't fit in RAM for regardless - this targets the 32-bit
 * Arduino cores (ESP32/ESP8266, and likely any other core shipping this same
 * "HTTPClient" library API) only. A board using a differently-shaped HTTP
 * library (e.g. WiFiNINA's ArduinoHttpClient) needs its own
 * IEmiHttpTransport - swap this file for one written against that library
 * instead, same interface.
 *
 * Generated by the Emi compiler - do not edit by hand.
 */
#pragma once

#ifndef ARDUINO
#error "EmiHttpTransportArduino.hpp requires the Arduino framework (ARDUINO is not defined) - include EmiHttpTransportCurl.hpp or EmiHttpTransportEspIdf.hpp instead."
#endif

#include "EmiHttpTransport.hpp"

#include <Arduino.h>
#include <Client.h>
#include <HTTPClient.h>

namespace emi {

class EmiHttpTransportArduino : public IEmiHttpTransport {
public:
    explicit EmiHttpTransportArduino(Client& client) : client_(client) {}

    EmiHttpResponse Send(const EmiHttpRequest& request) override {
        EmiHttpResponse response;
        HTTPClient http;
        if (!http.begin(client_, request.url.c_str())) {
            response.ok = false;
            response.error = "HTTPClient::begin failed";
            return response;
        }
        if (!request.body.empty()) {
            http.addHeader("Content-Type", "application/json");
        }
        for (const auto& h : request.headers) {
            http.addHeader(h.name.c_str(), h.value.c_str());
        }

        int status = http.sendRequest(
            request.method.c_str(),
            request.body.empty() ? nullptr : (uint8_t*) request.body.data(),
            request.body.size());

        if (status < 0) {
            response.ok = false;
            response.error = HTTPClient::errorToString(status).c_str();
        } else {
            response.statusCode = status;
            response.body = http.getString().c_str();
            response.ok = status < 400;
        }

        http.end();
        return response;
    }

private:
    Client& client_;
};

} // namespace emi
