/*
 * EmiHttpTransportCurl - the reference IEmiHttpTransport implementation, for
 * desktop/POSIX targets. Link against libcurl (`-lcurl`).
 *
 * Generated by the Emi compiler - do not edit by hand.
 */
#pragma once

#include "EmiHttpTransport.hpp"

#include <curl/curl.h>

namespace emi {

class EmiHttpTransportCurl : public IEmiHttpTransport {
public:
    EmiHttpResponse Send(const EmiHttpRequest& request) override {
        EmiHttpResponse response;

        CURL* curl = curl_easy_init();
        if (!curl) {
            response.ok = false;
            response.error = "curl_easy_init failed";
            return response;
        }

        std::string buffer;
        curl_easy_setopt(curl, CURLOPT_URL, request.url.c_str());
        curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, request.method.c_str());
        curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, &EmiHttpTransportCurl::WriteCallback);
        curl_easy_setopt(curl, CURLOPT_WRITEDATA, (void*) &buffer);

        struct curl_slist* headers = nullptr;
        for (const auto& h : request.headers) {
            std::string line = h.name + ": " + h.value;
            headers = curl_slist_append(headers, line.c_str());
        }
        if (!request.body.empty()) {
            headers = curl_slist_append(headers, "Content-Type: application/json");
            curl_easy_setopt(curl, CURLOPT_POSTFIELDS, request.body.c_str());
            curl_easy_setopt(curl, CURLOPT_POSTFIELDSIZE, (long) request.body.size());
        }
        curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);

        CURLcode result = curl_easy_perform(curl);
        if (result != CURLE_OK) {
            response.ok = false;
            response.error = curl_easy_strerror(result);
        } else {
            long status = 0;
            curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &status);
            response.statusCode = (int32_t) status;
            response.body = buffer;
            response.ok = status < 400;
        }

        curl_slist_free_all(headers);
        curl_easy_cleanup(curl);
        return response;
    }

private:
    static size_t WriteCallback(char* ptr, size_t size, size_t nmemb, void* userdata) {
        std::string* out = (std::string*) userdata;
        out->append(ptr, size * nmemb);
        return size * nmemb;
    }
};

} // namespace emi
