/*
 * EmiJson - the "no fixed shape" fallback type for `any`/unresolved `complex`/
 * unresolved `map` fields in the generic C++ dialect - the same role EmiAnyCodable
 * plays in the Swift target (lib/swift/swift-any-codable.go) or a bare `cJSON*`
 * plays in the C target (lib/c). Owns a standalone cJSON tree (never a view into
 * someone else's), so copies are always deep and lifetimes are never shared -
 * exactly the ownership convention every generated class's own ToJson()/FromJson()
 * follows in this target.
 *
 * Generated by the Emi compiler - do not edit by hand.
 */
#pragma once

#include "cjson/cJSON.h"

#include <string>

namespace emi {

class EmiJson {
public:
    EmiJson() : root_(nullptr) {}

    // Takes ownership of an existing cJSON tree (e.g. straight out of
    // cJSON_GetObjectItemCaseSensitive + cJSON_Duplicate, or cJSON_Parse).
    explicit EmiJson(cJSON* owned) : root_(owned) {}

    EmiJson(const EmiJson& other) : root_(other.root_ ? cJSON_Duplicate(other.root_, true) : nullptr) {}

    EmiJson(EmiJson&& other) noexcept : root_(other.root_) { other.root_ = nullptr; }

    EmiJson& operator=(const EmiJson& other) {
        if (this != &other) {
            cJSON_Delete(root_);
            root_ = other.root_ ? cJSON_Duplicate(other.root_, true) : nullptr;
        }
        return *this;
    }

    EmiJson& operator=(EmiJson&& other) noexcept {
        if (this != &other) {
            cJSON_Delete(root_);
            root_ = other.root_;
            other.root_ = nullptr;
        }
        return *this;
    }

    ~EmiJson() { cJSON_Delete(root_); }

    bool IsNull() const { return root_ == nullptr; }

    // Never owned by the caller - stays valid exactly as long as this EmiJson does.
    cJSON* Raw() const { return root_; }

    // Adopts an existing cJSON tree, releasing whatever this instance held before.
    void Reset(cJSON* owned) {
        if (root_ == owned) return;
        cJSON_Delete(root_);
        root_ = owned;
    }

    // Returns a new cJSON tree the caller owns (a deep copy, or cJSON_CreateNull()
    // when this EmiJson is itself null) - matches every generated ToJson() field's
    // "always hand back something cJSON_AddItemToObject can take" convention.
    cJSON* Clone() const { return root_ ? cJSON_Duplicate(root_, true) : cJSON_CreateNull(); }

    static EmiJson Parse(const std::string& text) { return EmiJson(cJSON_Parse(text.c_str())); }

    std::string Dump() const {
        if (!root_) return "null";
        char* rendered = cJSON_PrintUnformatted(root_);
        std::string out = rendered ? rendered : "null";
        cJSON_free(rendered);
        return out;
    }

private:
    cJSON* root_;
};

} // namespace emi
