/*
 * EmiSha1Base64 - minimal SHA-1 + base64, used only to compute the
 * Sec-WebSocket-Accept handshake value (RFC 6455 4.2.2) inside EmiWebSocketX.
 * Nothing cryptographic depends on this being constant-time or hardened - it
 * exists purely so the websocket handshake has zero external dependencies.
 *
 * Generated by the Emi compiler - do not edit by hand.
 */
#pragma once

#include <cstdint>
#include <cstring>
#include <string>

namespace emi {
namespace detail {

class EmiSha1 {
public:
    EmiSha1() { Reset(); }

    void Reset() {
        state_[0] = 0x67452301;
        state_[1] = 0xEFCDAB89;
        state_[2] = 0x98BADCFE;
        state_[3] = 0x10325476;
        state_[4] = 0xC3D2E1F0;
        bitLength_ = 0;
        bufferLength_ = 0;
    }

    void Update(const uint8_t* data, size_t len) {
        bitLength_ += uint64_t(len) * 8;
        AppendToBuffer(data, len);
    }

    // Writes the 20-byte digest into `out`. Do not call Update() again afterward
    // without a Reset() first.
    void Final(uint8_t out[20]) {
        uint64_t bitLength = bitLength_;

        uint8_t pad = 0x80;
        AppendToBuffer(&pad, 1);
        uint8_t zero = 0x00;
        while (bufferLength_ != 56) {
            AppendToBuffer(&zero, 1);
        }
        uint8_t lengthBytes[8];
        for (int i = 0; i < 8; i++) {
            lengthBytes[i] = (uint8_t) (bitLength >> (56 - 8 * i));
        }
        AppendToBuffer(lengthBytes, 8);

        for (int i = 0; i < 5; i++) {
            out[i * 4 + 0] = (uint8_t) (state_[i] >> 24);
            out[i * 4 + 1] = (uint8_t) (state_[i] >> 16);
            out[i * 4 + 2] = (uint8_t) (state_[i] >> 8);
            out[i * 4 + 3] = (uint8_t) (state_[i]);
        }
    }

private:
    // Appends raw bytes to the internal block buffer, flushing (and hashing) full
    // 64-byte blocks as they fill up. Unlike Update(), never advances
    // `bitLength_` - Final() relies on that to pad/append the length field
    // without the length field's own bytes counting themselves.
    void AppendToBuffer(const uint8_t* data, size_t len) {
        while (len > 0) {
            size_t take = 64 - bufferLength_;
            if (take > len) take = len;
            std::memcpy(buffer_ + bufferLength_, data, take);
            bufferLength_ += take;
            data += take;
            len -= take;
            if (bufferLength_ == 64) {
                ProcessBlock(buffer_);
                bufferLength_ = 0;
            }
        }
    }

    static uint32_t Rol(uint32_t value, int bits) { return (value << bits) | (value >> (32 - bits)); }

    void ProcessBlock(const uint8_t block[64]) {
        uint32_t w[80];
        for (int i = 0; i < 16; i++) {
            w[i] = (uint32_t(block[i * 4]) << 24) | (uint32_t(block[i * 4 + 1]) << 16) |
                   (uint32_t(block[i * 4 + 2]) << 8) | uint32_t(block[i * 4 + 3]);
        }
        for (int i = 16; i < 80; i++) {
            w[i] = Rol(w[i - 3] ^ w[i - 8] ^ w[i - 14] ^ w[i - 16], 1);
        }

        uint32_t a = state_[0], b = state_[1], c = state_[2], d = state_[3], e = state_[4];

        for (int i = 0; i < 80; i++) {
            uint32_t f, k;
            if (i < 20) {
                f = (b & c) | ((~b) & d);
                k = 0x5A827999;
            } else if (i < 40) {
                f = b ^ c ^ d;
                k = 0x6ED9EBA1;
            } else if (i < 60) {
                f = (b & c) | (b & d) | (c & d);
                k = 0x8F1BBCDC;
            } else {
                f = b ^ c ^ d;
                k = 0xCA62C1D6;
            }

            uint32_t temp = Rol(a, 5) + f + e + k + w[i];
            e = d;
            d = c;
            c = Rol(b, 30);
            b = a;
            a = temp;
        }

        state_[0] += a;
        state_[1] += b;
        state_[2] += c;
        state_[3] += d;
        state_[4] += e;
    }

    uint32_t state_[5];
    uint64_t bitLength_;
    uint8_t buffer_[64];
    size_t bufferLength_;
};

inline std::string EmiBase64Encode(const uint8_t* data, size_t len) {
    static const char* table = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    std::string out;
    out.reserve(((len + 2) / 3) * 4);

    size_t i = 0;
    while (i + 3 <= len) {
        uint32_t n = (uint32_t(data[i]) << 16) | (uint32_t(data[i + 1]) << 8) | uint32_t(data[i + 2]);
        out.push_back(table[(n >> 18) & 0x3F]);
        out.push_back(table[(n >> 12) & 0x3F]);
        out.push_back(table[(n >> 6) & 0x3F]);
        out.push_back(table[n & 0x3F]);
        i += 3;
    }

    size_t remaining = len - i;
    if (remaining == 1) {
        uint32_t n = uint32_t(data[i]) << 16;
        out.push_back(table[(n >> 18) & 0x3F]);
        out.push_back(table[(n >> 12) & 0x3F]);
        out.push_back('=');
        out.push_back('=');
    } else if (remaining == 2) {
        uint32_t n = (uint32_t(data[i]) << 16) | (uint32_t(data[i + 1]) << 8);
        out.push_back(table[(n >> 18) & 0x3F]);
        out.push_back(table[(n >> 12) & 0x3F]);
        out.push_back(table[(n >> 6) & 0x3F]);
        out.push_back('=');
    }

    return out;
}

} // namespace detail
} // namespace emi
