/*
 * EmiWebSocketX - a minimal, dependency-free RFC 6455 client, backing every
 * `method: reactive` action in the generic C++ dialect (see
 * cpp-action-reactive-render.go) - the same role EmiWebSocketX plays in the Swift
 * target (lib/swift/swift-websocket-runtime.go) and WebSocketX in the JS target.
 * Speaks over any IEmiByteStream (see EmiByteStream.hpp), so the exact same
 * handshake/framing code here runs unmodified on desktop, ESP-IDF, and Arduino.
 *
 * Scope boundary (documented, not an oversight - mirrors the C target's own
 * fetchx.h note on SSE not being truly streaming): only single-frame text/binary
 * messages are handled (no fragmentation, no permessage-deflate) - more than
 * enough for the small, single JSON-object payloads a `method: reactive` action
 * exchanges, but not a general-purpose WebSocket client. `wss://` needs a
 * TLS-capable IEmiByteStream (e.g. WiFiClientSecure via EmiByteStreamArduino) -
 * EmiByteStreamPosix is plain TCP only.
 *
 * Generated by the Emi compiler - do not edit by hand.
 */
#pragma once

#include "EmiByteStream.hpp"
#include "EmiSha1Base64.hpp"

#include <cctype>
#include <cstdlib>
#include <functional>
#include <string>

namespace emi {

enum class EmiWebSocketState { Closed, Connecting, Open };

class EmiWebSocketX {
public:
    using MessageHandler = std::function<void(const std::string&)>;
    using ErrorHandler = std::function<void(const std::string&)>;
    using CloseHandler = std::function<void()>;

    // `stream` must stay alive for as long as this EmiWebSocketX is used - not owned.
    explicit EmiWebSocketX(IEmiByteStream& stream) : stream_(stream) {}

    MessageHandler onMessage;
    ErrorHandler onError;
    CloseHandler onClose;

    // `url` is a plain `ws://host[:port]/path` url (build one with EmiBuildUrl and
    // a scheme swap - see the generated `*Socket::Create` helper). Blocking -
    // returns once the RFC 6455 handshake has completed (or failed).
    bool Connect(const std::string& url) {
        std::string host, path;
        uint16_t port = 80;
        if (!ParseUrl(url, host, port, path)) {
            Fail("invalid websocket url: " + url);
            return false;
        }
        if (!stream_.Connect(host, port)) {
            Fail("failed to connect to " + host);
            return false;
        }
        if (!PerformHandshake(host, path)) {
            stream_.Close();
            Fail("websocket handshake failed");
            return false;
        }
        state_ = EmiWebSocketState::Open;
        return true;
    }

    // Sends one text frame - the wire format every generated dto's JSON payload
    // round-trips through. Client-to-server frames are always masked (RFC 6455 5.1).
    bool Send(const std::string& text) {
        if (state_ != EmiWebSocketState::Open) return false;
        return SendFrame(0x1, (const uint8_t*) text.data(), text.size());
    }

    // Blocks until exactly one frame has been read and dispatched (via onMessage/
    // onError/onClose as appropriate), or the stream reports the connection is
    // gone. Call this in a loop from the platform's own task/loop (Arduino's
    // `loop()`, a dedicated ESP-IDF task, or a background thread on desktop) -
    // this runtime has no timers or event loop of its own.
    void Poll() {
        if (state_ != EmiWebSocketState::Open) return;

        uint8_t header[2];
        if (!ReadExact(header, 2)) {
            HandleDisconnect();
            return;
        }

        bool fin = (header[0] & 0x80) != 0;
        uint8_t opcode = header[0] & 0x0F;
        bool masked = (header[1] & 0x80) != 0;
        uint64_t length = header[1] & 0x7F;

        if (length == 126) {
            uint8_t ext[2];
            if (!ReadExact(ext, 2)) {
                HandleDisconnect();
                return;
            }
            length = (uint16_t(ext[0]) << 8) | ext[1];
        } else if (length == 127) {
            uint8_t ext[8];
            if (!ReadExact(ext, 8)) {
                HandleDisconnect();
                return;
            }
            length = 0;
            for (int i = 0; i < 8; i++) length = (length << 8) | ext[i];
        }

        uint8_t maskKey[4] = {0, 0, 0, 0};
        if (masked && !ReadExact(maskKey, 4)) {
            HandleDisconnect();
            return;
        }

        std::string payload;
        payload.resize((size_t) length);
        if (length > 0 && !ReadExact((uint8_t*) &payload[0], (size_t) length)) {
            HandleDisconnect();
            return;
        }
        if (masked) {
            for (size_t i = 0; i < payload.size(); i++) {
                payload[i] = (char) ((uint8_t) payload[i] ^ maskKey[i % 4]);
            }
        }

        if (!fin) {
            // A fragmented frame isn't supported (see the class doc) - surfaced as
            // an error rather than silently truncated/misdelivered.
            if (onError) onError("received a fragmented websocket frame (unsupported)");
            return;
        }

        switch (opcode) {
            case 0x1: // text
            case 0x2: // binary
                if (onMessage) onMessage(payload);
                break;
            case 0x8: // close
                stream_.Close();
                state_ = EmiWebSocketState::Closed;
                if (onClose) onClose();
                break;
            case 0x9: // ping - answer with pong, per RFC 6455 5.5.2
                SendFrame(0xA, (const uint8_t*) payload.data(), payload.size());
                break;
            case 0xA: // pong - nothing to do
                break;
            default:
                break;
        }
    }

    bool IsOpen() const { return state_ == EmiWebSocketState::Open; }

    void Close() {
        if (state_ == EmiWebSocketState::Open) {
            SendFrame(0x8, nullptr, 0);
        }
        stream_.Close();
        state_ = EmiWebSocketState::Closed;
    }

private:
    void Fail(const std::string& message) {
        state_ = EmiWebSocketState::Closed;
        if (onError) onError(message);
    }

    void HandleDisconnect() {
        state_ = EmiWebSocketState::Closed;
        stream_.Close();
        if (onClose) onClose();
    }

    bool ReadExact(uint8_t* buffer, size_t length) {
        size_t got = 0;
        while (got < length) {
            int n = stream_.Read(buffer + got, length - got);
            if (n <= 0) return false;
            got += (size_t) n;
        }
        return true;
    }

    bool SendFrame(uint8_t opcode, const uint8_t* payload, size_t length) {
        std::string frame;
        frame.push_back((char) (0x80 | opcode)); // FIN=1, single-frame only

        uint8_t maskKey[4];
        for (auto& b : maskKey) b = (uint8_t) (std::rand() & 0xFF);

        if (length < 126) {
            frame.push_back((char) (0x80 | length)); // MASK=1
        } else if (length <= 0xFFFF) {
            frame.push_back((char) (0x80 | 126));
            frame.push_back((char) ((length >> 8) & 0xFF));
            frame.push_back((char) (length & 0xFF));
        } else {
            frame.push_back((char) (0x80 | 127));
            for (int i = 7; i >= 0; i--) frame.push_back((char) ((length >> (8 * i)) & 0xFF));
        }
        frame.append((const char*) maskKey, 4);

        size_t offset = frame.size();
        frame.resize(offset + length);
        for (size_t i = 0; i < length; i++) {
            frame[offset + i] = (char) (payload[i] ^ maskKey[i % 4]);
        }

        return stream_.Write((const uint8_t*) frame.data(), frame.size());
    }

    static bool ParseUrl(const std::string& url, std::string& host, uint16_t& port, std::string& path) {
        std::string rest = url;
        if (rest.rfind("ws://", 0) == 0) {
            rest = rest.substr(5);
            port = 80;
        } else if (rest.rfind("wss://", 0) == 0) {
            rest = rest.substr(6);
            port = 443;
        } else {
            return false;
        }

        size_t slash = rest.find('/');
        std::string authority = slash == std::string::npos ? rest : rest.substr(0, slash);
        path = slash == std::string::npos ? "/" : rest.substr(slash);

        size_t colon = authority.find(':');
        if (colon == std::string::npos) {
            host = authority;
        } else {
            host = authority.substr(0, colon);
            port = (uint16_t) std::atoi(authority.substr(colon + 1).c_str());
        }
        return !host.empty();
    }

    bool PerformHandshake(const std::string& host, const std::string& path) {
        uint8_t keyBytes[16];
        for (auto& b : keyBytes) b = (uint8_t) (std::rand() & 0xFF);
        std::string key = detail::EmiBase64Encode(keyBytes, 16);

        std::string request = "GET " + path + " HTTP/1.1\r\n"
            "Host: " + host + "\r\n"
            "Upgrade: websocket\r\n"
            "Connection: Upgrade\r\n"
            "Sec-WebSocket-Key: " + key + "\r\n"
            "Sec-WebSocket-Version: 13\r\n\r\n";

        if (!stream_.Write((const uint8_t*) request.data(), request.size())) return false;

        std::string response;
        char byte;
        // A raw byte-at-a-time read keeps this free of any dependency on a
        // buffered-line reader - fine for a one-shot, small HTTP response header.
        while (response.size() < 8192) {
            int n = stream_.Read((uint8_t*) &byte, 1);
            if (n <= 0) return false;
            response.push_back(byte);
            if (response.size() >= 4 && response.compare(response.size() - 4, 4, "\r\n\r\n") == 0) {
                break;
            }
        }

        if (response.find(" 101 ") == std::string::npos) return false;

        std::string expectedAccept = ComputeAcceptKey(key);
        std::string needle = "Sec-WebSocket-Accept:";
        size_t pos = FindHeaderCaseInsensitive(response, needle);
        if (pos == std::string::npos) return false;

        size_t valueStart = pos + needle.size();
        while (valueStart < response.size() && response[valueStart] == ' ') valueStart++;
        size_t valueEnd = response.find("\r\n", valueStart);
        std::string actualAccept = response.substr(valueStart, valueEnd - valueStart);

        return actualAccept == expectedAccept;
    }

    static size_t FindHeaderCaseInsensitive(const std::string& response, const std::string& name) {
        std::string lowerResponse = response;
        std::string lowerName = name;
        for (auto& c : lowerResponse) c = (char) std::tolower((unsigned char) c);
        for (auto& c : lowerName) c = (char) std::tolower((unsigned char) c);
        // Offsets line up 1:1 with `response` since only the local copies were lowercased.
        return lowerResponse.find(lowerName);
    }

    static std::string ComputeAcceptKey(const std::string& clientKey) {
        static const char* magic = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11";
        std::string combined = clientKey + magic;
        detail::EmiSha1 sha1;
        sha1.Update((const uint8_t*) combined.data(), combined.size());
        uint8_t digest[20];
        sha1.Final(digest);
        return detail::EmiBase64Encode(digest, 20);
    }

    IEmiByteStream& stream_;
    EmiWebSocketState state_ = EmiWebSocketState::Closed;
};

} // namespace emi
